### ISSUE TITLE
Please implement Google Yolo as a default sign in/sign up method

### ISSUE THREAD

**Issue by kyvaith** [DivanteLtd/vue-storefront#1010]
Would be great to get a native sign in/sign up mechanisms on three major platforms (Google, Apple, Microsoft). Lets start with Google: https://developers.google.com/identity/one-tap/web/
Its implemented on Polymer demo store: https://polykart-credential-payment.appspot.com/list/mens_tshirts

**Comment by pkarw** [comment]
Thanks, good point. We definitely should consider this integration. It's to be checked how it will involve the Magento / Custom backend Authorization mechanisms - and how should we integrate with them

**Comment by kyvaith** [comment]
IMO by pushing password-less account entity to Magento DB, but I'm not a developer. Do you assume direct Magento login for implementations using vue-storefrontend?

**Comment by pkarw** [comment]
We're relying on the backend authorization and personal data storage - and we don't have any personal data stored in Elastic/Mongo etc. So it's for a discussion (because it must be integrated and integrated with all the possible backends - Magento1, Magento2, Pimcore). We're using general JS tokens based authorization mechanism against some central databsae (for example on demo.vuestorefront.io it's demo-magento2.vuestorefront.io to take care of authorizing users). VS doesn't have backend storage/support for authorization and it's not planned to have it
