### ISSUE TITLE
Optimize the Home page slider (image sizes) + Lightouse performance results

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#1019]
The performance got degraded during the active development of last few months. We need to run som Lightouse reports and focus on bringing it back :)

Who's excited for this challenge? :-)

**Comment by HRR1337** [comment]
Hi there,

First short suggestion: Images..

- Example image: slider 1 https://demo.vuestorefront.io/assets/slide_01.jpg

 is 2880*1280 .. thats way to large. if you make it 1920 thats already more then enough, and set the quality to 0 (yes, really, in photoshop).. will not make a big (almost non) difference, and the size will go down from 168kb to 33kb.. 

What I do personally is serving .webp where possible. Have done that serverside. When a browser can accept .webp it serves .jpg.webp files instead of .jpg  It make a big difference! And I use this command to find the images in a directory and convert them to .webp

find . -iname '*.jpg' | parallel --eta convert '{}' -format webp -quality 85 '{}'.webp \;

Looks also that on the slideshow, every image is needed to load, even though the first image is only visisble.

Also regarding the other images on the page. Lazyloading is not active at this moment?

-- bit optimised images..

![slide_01](https://user-images.githubusercontent.com/4428675/38931227-bc889d60-4312-11e8-97ca-5d8da55fad87.jpg)
![slide_03](https://user-images.githubusercontent.com/4428675/38931228-bc9ff622-4312-11e8-9781-4be4ae3fb556.jpg)
![slide_02](https://user-images.githubusercontent.com/4428675/38931229-bcb6fee4-4312-11e8-80ec-c33b44a46add.jpg)

**Comment by pkarw** [comment]
Thanks @HRR1337 - great insights. We've implemented quite a few optimizations last week, preparing to the Magento Imagine; Could you please prepare a PR with Your's ideas? Please check out latest develop

**Comment by pkarw** [comment]
@HRR1337 maybe You can take this one?
