### ISSUE TITLE
  Core modules[proposal, discussion] 

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#1213]
Hi!
For now we are using core components and pages to develop our stores which works well but have some drawbacks that can be fixed:

- The functionalities are grouped in component-structure-oriented way rather that feature-oriented which is not the best approach for a modular application
- It kind of forces people to use same component structure for each store which doesn't play well with implementations that are much different than our default theme
- Core components are rather complex, it's hard to reason about them and even harder to change only the parts that we want to work different
- People can't tell what are the features of the component just by looking at it - you need to jump into the code and understand it
- Methods inside core components are tightly copupled which isn't good for refactoring and modifying some functions  in the future
- It's hard to reason what comes from core and what comes from theme if both are bulky and complicated
- We are injecting whole components even when we only want one or two features which ends up as bulky components with redundant functionalities
- You basically can't say what you can do with the core without understanding it in-depth
- its nearly impossible to tell people which functions are part of the CORE API so they can rely on them and use in their themes and which are just helper functions 

**What is the proposed fix?**

The idea is to group similar functionalities into modules. Also I'll try to split current core components into smaller standalone features (like add to cart, remove from cart, items in car  etc). it's still meant to be used as mixins but now you will export exactly what you want and will know exactly what you are injecting 

You can find two proposal modules here ( https://github.com/filrak/vue-storefront/tree/modules-and-catalog-theme/core/modules )The implementation of this particular modules will (for sure) change but it's just to get the idea.

So now instead of bunch of core components for let's say cart we will have `cart` module with following mixins to import: `cart_add(product)`, `cart_remove(product)`, `cart_items`, `cart_isInCart(product)` etc. So we can for example import only `cart_isInCart()` mixin to our product listing to tell the user that this item is in cart. Now we will need to import whole `microcart` module or copy this method from inside of the core to achieve this.

The proposed API for using it will be as follows.

`modulePrefix_methodOrDataname` - so you can see from the beginning in your theme's code that this functionality is a core functionality coming from module X.

1. You can import all parts of the module (including every data property and method related to this module) and inject:
````js
import CartModule from 'core/modules/cart'
...
mixins: [CartModule]
````
2....or just the ones that you need (this particular set would be useful for Product page)
````js
import { cart_add, cart_remove } from 'core/modules/cart'
...
mixins: [cart_add, cart_remove]
````
Similar modules would be created for wishlist, menu, categories, product, compare etc.

Such modularisation and abstraction will also hide the helper functions so we can refactor and improve our core much efficient without bothering about all legacy code and focusing only on keeping the core exported functions untouched with its API

Ofc we can still have some core components that will just group features from one or many modules that are commonly grouped together but it would be  a little help and addition to speed up some very common taska, not the core itself that we must always use. 

The core pages with their core functionalities will probably stay as they are with small refactoring but this one is still to be discussed (probably having 3-4 pages like this will be still transparent for developers) 

Please let me know what do you think about this API, how do you see the improvements and what else can be improved during this API change.

You can find previous discussion here: https://github.com/DivanteLtd/vue-storefront/pull/1184

**Comment by patrykpiston** [comment]
I like the idea, It would make it easier to use just the parts one needs. As you said it will give way more flexibility to someone who wants to create something on top of VS with a totally different interface in mind.

**Comment by michael-kaufman** [comment]
As someone 2 weeks into this code, I agree and like the Modular approach. It does get rather tricky to know what comes from where exactly. Having duplicate folder names in different places is a little confusing too. Perhaps refactoring folder names to make it clear for e.g. core-logic vs core-theme or plug-in-logic vs plug-in-theme; or something similar would help too.  Thanks!

**Comment by Triloworld** [comment]
Nice idea (and work!), VUE is for simplicity and development experience. I don't like second and more layer above existing in vue, because people use it for that simple approach.

I check that module directory and is clearly better approach to some problems. 
One problem is the most obvious, used grouped functionality or simple one? maybe just use vuex? 
Maybe "core/api" as showed in description. It's obvious that all my functions and data need to be taken from that one directory, otherwise I break site in future. Beside, more like to camelCase :D than some fancy underscore

`import { cartAdd, cartRemove, cartReload, cartUpdate } from 'core/api/cart'`

Internally writing test for that "api" directory will be in high demand to determine if something will break after refactor - right now, only one test :(.

**Comment by nuovecode** [comment]
I'm torn. On the one hand I like the idea of using a more modular approach for components, on the other hand we risk complicating the file and folder structure too much. Now It's quite easy to understand how components works just looking at the code, to split them into more granular components without losing the current (awesome) semplicity it will be a great challenge. 
But, you are right, it's time to do it, especially for the benefit of the scalability of the framework.  

The structure of the folders of the components could follow that of the vuex store (attribute, cart, category..) ? this would perhaps help to orientate within the core.

**Comment by pkarw** [comment]
Great discussion!

I’m afraid of this approach because of the following arguments:
- modules - it’s another layer of abstraction for the newcomers; it’s a little bit  mess with the vuex modules and src/extensions 
- I agree with Irene, it’s now far easier to understand the structure of the Ui with more granulated components - we’ll probably lost it it with modules
- I don’t see easy way to do the automatic update of the code people already have developed (custom themes)
- the naming convention with lower case - for some it’s better than UpperCase - but the fact is that will require lot of manual changes just for sake of let’s say “visual preference” ;)
- how to combine this approach with Vuex stores?
- module_component - it’s very very Magento’ish :)
- For now we have the components structure fairly easy to understand because you always start with the theme *.vue file having clear relation to the core components; with modules it’s gone; you must digg thru modules to find components you require; we don’t have capacity to maintain full blown docs at the moment to deal with this issue probably

**Comment by pkarw** [comment]
Maybe sth with satisfy all  is to stick with the current component structure AND add this module based mixins / logic separation?

Then we should have sth like core/api or sth - just with this set of logic mixins instead of modules to not mess with vuex modules.

In that case if somebody would like to create totally custom theme he or she can avoid the core/components and use the core/api instead

The naming convention with the moduleName_mixinName doesn’t speak to me anyway :) and should be discussed

It’s just for discussion, thinking aloud

**Comment by pkarw** [comment]
Exactly, core components grouping these more granular mixins - this makes sense for me!

**Comment by filrak** [comment]
Love to hear that ;d

**Comment by mercs600** [comment]
I agree with you guys! Core methods as mixins to couple some basic components it's good idea 🥇 
From my point of view it should be easier to maintenance, refactore and test. 

@pkarw you asked how can we combine these mixins with vuex.  In my opinion when we want to use some state/getter etc from vuex we should map this state in this mixin. 
So for example we have method addToCart, we should map mutation from cart module. Next we have removeFromCart we should also map mutation from cart module. I think it's not problem because when we load these mixins in cart component, everything should be merged. So it's shouldn't be a problem when we would like to use the same state in two different mixins which we attach to one component.

**Comment by DavidRouyer** [comment]
Modularization? Of course!

One mixin per file is perfectly fine for me.
I saw what you did in core/modules and I have a few remarks:
* Don't call your files add.js, products.js and remove.js: call them addToCart.js, productsInCart.js, removeFromCart.js (make you did this in a rush, much more readable).
* In these files, try:
```javascript
export const addToCart = {
  props: {
    product: {
      type: Object,
      required: true
    }
  },
  methods: {
    addToCart (product) {
      this.$store.dispatch('cart/addItem', { productToAdd: product })
    }
  }
}
```
instead of 
```javascript
export default {
  props: {
    product: {
      type: Object,
      required: true
    }
  },
  methods: {
    addToCart (product) {
      this.$store.dispatch('cart/addItem', { productToAdd: product })
    }
  }
}
```
If you use VS Code or another tool which understands ES6, the addToCart object should pop up in the autocomplete. In index.js:
```javascript
import { addToCart } from './addToCart'
import { removeFromCart } from './removeFromCart'
import { productsInCart } from './productsInCart'

export {
  addToCart,
  removeFromCart,
  productsInCart
}

```
And when you try to use it...
![import](https://user-images.githubusercontent.com/1556750/40690167-f7aede1e-63a5-11e8-8c43-bfcfa2943fd6.jpg)

We can also put the internal files in a internal folder. If you're a user and you're importing something from an internal folder, you do something terribly wrong, since we have no way to hide them.
![arch](https://user-images.githubusercontent.com/1556750/40690304-b592ca6c-63a6-11e8-9fc8-acc6d5b21bff.JPG)

If we want to go further, why not putting the vuex store module directly into the cart module folder? If you're working on the cart module, it's better to have everything in the same place. 
Take a look at https://medium.com/3yourmind/large-scale-vuex-application-structures-651e44863e2f and this approach:
![image](https://user-images.githubusercontent.com/1556750/40690428-52640338-63a7-11e8-9384-3764da256139.png)
"modules" can combine the vuex store module, the mixins, and even components!
I prefer the component-oriented or module-oriented approach over the classic vue approach.

**Comment by DavidRouyer** [comment]
Keep in mind that you
* Are not breaking anything when moving files (Vuex modules will work the same way, you import it differently) 
* You can change the folder structure and still be backward compatible by keeping the store folder (with the current index.js and exports which redirects to the new folders) 
* We can add JSDoc comments for example for depreciation warnings, or ESLint rules
