### ISSUE TITLE
Test + Fix MS Edge + IE10 support

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#1266]
![win7_ie_10 0](https://user-images.githubusercontent.com/211899/41129201-47de6686-6ab1-11e8-8838-8622d6f080a5.jpg)
![win10_ie_11 0](https://user-images.githubusercontent.com/211899/41129202-48019e3a-6ab1-11e8-964e-70bde97d8fc1.jpg)
![win10_edge_17 0](https://user-images.githubusercontent.com/211899/41129203-482353fe-6ab1-11e8-8859-36dfdcbed881.jpg)

**Comment by filrak** [comment]
IE 10 support requires rewriting default theme, for edge everything except unsupported enhancements like ` mix-blend-mode` for images works now

**Comment by dennisotugo** [comment]
Has this been fixed? Recent deployment does not work at all in IE 11

**Comment by pego** [comment]
@pkarw edge is working, ie10 & ie11 seems broken.

**Comment by pkarw** [comment]
OK, would be great to put all the required bugs on IE into issues and fix them one by one :)

**Comment by dennisotugo** [comment]
Sorry for the late reporting on this. @pkarw Nearly all functionality does not work on IE11. Buttons don't work and Product Images does not show likewise. We can start with these ones.

**Comment by pkarw** [comment]
@dennisotugo please do

**Comment by mdanilowicz** [comment]
I do some tests, but I am not a Webpack expert, so please correct me if I am wrong: 

VSF is not working on IE11 & 10 because there is ES6 code that IE is not supporting.
![2018-09-21_10h11_16](https://user-images.githubusercontent.com/7597086/45868715-c13bf700-bd86-11e8-8bdc-46e1f0897250.png)

This code appears there because we don't compile ES6 code in  node_module. 
```{
        test: /\.js$/,
        loader: 'babel-loader',
        include: [
          '@vue-storefront',
          path.resolve(__dirname, '../../src'),
          path.resolve(__dirname, '../../core')
        ]
      },```

When I added the node_mode path to babel configuration... application exploded :D.  After long hours of debugging and fixing webpack/babel problems, I ran VSF on IE. 

![2018-09-21_09h24_14](https://user-images.githubusercontent.com/7597086/45868974-71a9fb00-bd87-11e8-89c7-8ffc3905ddf4.png)

So, in my opinion, we should compile node_module code also. It would be great if someone with experience in webpack could check my theory and suggest the best method on how to fix this problem.

**Comment by pkarw** [comment]
Good point! We should aim the modules that are not compiled with Babel by their creator (as this Vue-offline show. On screen - made by @filrak hah ;)) and add exceptions for them (to compile them by Babel)

@mdanilowicz do you have maybe a kind of list from your research which modules need to be fixed?

**Comment by lorenaramonda** [comment]
Could someone try to replace stage-2 with stage-3 in .babelrc config? I tried on my project (which however is a lot of version behind) and it worked

**Comment by filrak** [comment]
@pkarw yeah right but there is a little bit more libs like this
