### ISSUE TITLE
Products attributes are multiplied after login

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#1281]
Steps to reproduce
1. Visit VS,
2. Log in
3. Go to the product page (from homepage)

After above steps you should see this:

![image](https://user-images.githubusercontent.com/15185752/41242546-21f383f6-6da0-11e8-9fb7-5cebb8878c26.png)

or even this
![image](https://user-images.githubusercontent.com/15185752/41242623-52218df2-6da0-11e8-9029-a38c6489c5f3.png)

**Comment by pkarw** [comment]
@filrak how about this one?

**Comment by pkarw** [comment]
I suggest You to use some global/store wide flag set in the `product/fetch` OR in the `ProductTile.vue` on click (maybe even better to put it here as it's clearly UI related issue, not Vuex one?) It should be cleared by kind of `setTimeout()` in case of exceptions / user derail from classical flow because it's - as all the mutexes - pretty risky to set some global lock :)

The second place to clear the flag probably should be cleared just in the https://github.com/DivanteLtd/vue-storefront/blob/de20561167fda0764451a50e68088a6a22d5a9cd/core/pages/Product.js#L127 ?

**Comment by pkarw** [comment]
This is fixed
