### ISSUE TITLE
After selecting a filter with specific color, in the gallery there are photos for all configurations.

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#1326]
1.  Visit Vuestorefront
2. Go to any category
3. Choose any product
4. Select color
5. Review available gallery 

**Actual results:**
There are photos for all configurations, not for specific color.
![image](https://user-images.githubusercontent.com/36628922/41699800-e8805d78-7525-11e8-8b6b-c5d1ee6d16a3.png)

**Expected:**
There should be photos only for specific color.

**Comment by pkarw** [comment]
You mean that the photo is not changing to the currently selected color (white in this case), right?

I mean -> photos of other colors should stay where they are, but we should have changed the current one for white

**Comment by pkarw** [comment]
This is related to: #1268 @nuovecode could You take care of this?

**Comment by alinadivante** [comment]
I mean two issue: the first one is actually reported (#1268 ) and the other: I assumed that by choosing a specific color I will have a photo gallery containing only clothes in that color

**Comment by pkarw** [comment]
Ok, the second point is a new feature / feature enchantment then :) could you create the second issue for it? The current, expected behavior is that it just should show the specific color photo, not filtering the gallery.

I agree that it would be useful feature, why not to add it?

**Comment by nuovecode** [comment]
Hi! can't find this bug. The steps I'm doing on https://demo.vuestorefront.io are:

1. Visit Vuestorefront
2. Go to category pants /c/pants-27
3. Choose  product "Portia Capri" (the first of the list)

_The gallery goes to selected color photo (blue)_

4. Select color green 

_The gallery goes to the green photo_

Ok to give the option to show only the photos of the selected option (and not the whole gallery) Issue: #1327.

For the bug you give me some more clues?

**Comment by alinadivante** [comment]
@nuovecode Hi! Try to switch to Orange color. After your steps + 4. Select the color orange -  I still see green

**Comment by pkarw** [comment]
Irene - let me wrap up the problem: the issue is wha to do with the images that are not attached to any specific color right?

First: we need to have a config option - current behavior of merging media_gallery and children images should still be available.

If the option switches the gallery behavior to this new one - we  can just filter out the media_gallery keeping just configurable children images for specific color

We should apply this logic only to configurable products! Simple/bundle products can also have media_gallery which is perfectly ok and should be still supported.

**Comment by pkarw** [comment]
we don’t plan to manage small, thumb ... images. Only media_gallery and images collected from the configurable_children
