### ISSUE TITLE
Page Links Not Redirecting

### ISSUE THREAD

**Issue by michaelsmith193** [DivanteLtd/vue-storefront#1362]
When I click any link on the app, it doesn't redirect me. When I right click and open in a new tab, it works. Any ideas??

**Comment by pkarw** [comment]
Could You please paste the developer tools console output?

**Comment by michaelsmith193** [comment]
you can view it on http://13.229.73.65/

**Comment by michaelsmith193** [comment]
Log: http://textuploader.com/dzow4

I just tried Safari, and the Sidebar doesn't even open

**Comment by pkarw** [comment]
OK, it works for me because I've got a localhost:8080 api runing on my machine. 
You haven't changed the endpoint URLs and elasticsearch url in the config/local.json - and it ends up trying to get the data from localhost:8080 which is default.

Please find & replace all the `localhost` references in the config/local.json with the proper API endpoints https://www.dropbox.com/s/ndw29ep33hro1j2/Screenshot%202018-06-26%2008.14.13.png?dl=0

**Comment by michaelsmith193** [comment]
So I replace it with my Magento URL ?

**Comment by michaelsmith193** [comment]
what is vue-storefront-api? So 13.229.73.65:8080?

**Comment by pkarw** [comment]
No idea :) It depends on where You've installed it :)

**Comment by michaelsmith193** [comment]
Isn't it default installed on localhost:8080

**Comment by michaelsmith193** [comment]
I tried running the vue-storefront-api on both localhost:8080 and 0.0.0.0:8080. Put 13.229.73.65:8080 on the config/local.json file but couldn't access both of them, and get { Error: Request Timeout after 5000ms ..... }

**Comment by pkarw** [comment]
Please check Yout firewall settings

**Comment by michaelsmith193** [comment]
Thanks so much :) It was the firewall settings in Ec2
