### ISSUE TITLE
Flow.org type checking

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#1458]
I believe it would be much easier for developers to work with the Vue Storefront core if we introduce the static type checking (https://flow.org/en/) in some parts of the core app.

I believe that for the PoC we could introduce Flow infrastructure to the project and then add the type definitions to the:
- [ ] Vuex cart module (addItem) 
- [ ] Vuex product module (list, single)
- [ ] Core Pages (with subcomponents) - Product, Category.

After having this in place we can plan further refactoring

@Igloczek @filrak what do You think guys?

**Comment by filrak** [comment]
We should also create sam basic interfaces for products orders etc containing fields that we are refering in ui and business logic

**Comment by patrykpiston** [comment]
I'd be happy to take that task.

**Comment by pkarw** [comment]
@patrykpiston that's cool - please go for it and start the task - we'll be having a Hackathon in Poznań on Friday - do You think that it's possible to do some infrastructure before Friday to let the guys take care of some  part of this refactor, as it's pretty broad topic?

**Comment by patrykpiston** [comment]
Unfortunately I was not able to implement flow into the project. I got it to work in the single .js files [(my branch)](https://github.com/patrykpiston/vue-storefront/tree/feature/flow-system-integration) but only by using this [webpack loader](https://www.npmjs.com/package/remove-flow-types-loader), and using very strict formatting rules. This meant only one liners when setting types of variables, and other features such as interfaces did not work, so it's basically useless.

All of this because Flow, to work correctly in a project like this, has to be integrated into the _eslint_ pipeline, and the current parser _vue-eslint-parser_ does not recognize rules set by flow plugins, or vice-versa. It works with _babel-eslint_ but I think we cannot use that one here.

Basically what is happening is that we have plugins to transform Flow syntax into plain JS with babel plugins:
- [babel-plugin-syntax-flow](https://www.npmjs.com/package/babel-plugin-syntax-flow)
- [babel-plugin-transform-class-properties](https://www.npmjs.com/package/babel-plugin-transform-class-properties)
- [babel-plugin-transform-flow-strip-types](babel-plugin-transform-flow-strip-types)

But we cannot use them since build always fails during linting, as we need untouched source files to be checked by Flow, preferably with all the webpack variables and aliases. Otherwise we would need workarounds like these: [patrykpiston/vue-storefront/.flowconfig](https://github.com/patrykpiston/vue-storefront/blob/feature/flow-system-integration/.flowconfig)

Also if we could use babel plugins with eslint parser which cooperates, it would be easy to use Flow. Maybe there is a way to do it, so maybe somebody will be able to implement it correctly.

Different github issues describing the problem:
- [flowtype-errors and plugin-vue do not work together](https://github.com/vuejs/eslint-plugin-vue/issues/224)
- [Can't use this parser with flow types](https://github.com/mysticatea/vue-eslint-parser/issues/10)
- ['error Unexpected token' then combined with 'vue-eslint-parser'](https://github.com/amilajack/eslint-plugin-flowtype-errors/issues/95)

**Comment by filrak** [comment]
So maybe TS ;)

**Comment by patrykpiston** [comment]
Sure :)
I remember we talked about TS with Vue, wouldn't that bring too much change in the project? Just asking, I'm sure it would work since Vue has more or less, a native support for TS ;)

**Comment by pkarw** [comment]
I'm closing this one as we have the TypeScript included :)
