### ISSUE TITLE
One-word component names

### ISSUE THREAD

**Issue by lorenaramonda** [DivanteLtd/vue-storefront#1596]
I've noticed that there are components named with only one word, this is [strongly discourage by Vue style guide](https://vuejs.org/v2/style-guide/#Multi-word-component-names-essential) and W3C specifications because it could encounter conflicts in future HTML5 tags.

Maybe we should think about a refactoring of these components name? 😁

**Comment by pkarw** [comment]
My opinion is: it would be good to refactor it, but how about the backward compatibility? I think it would be much easier to develop new theme (and we're designing one from scratch now) to improve this and other architectureal/component things; rather than pushing incremental changes to the existing theme

WDYT?

**Comment by lorenaramonda** [comment]
Yes, I didn't know about the "new theme" project until one hour ago when I talked with @filrak . Now that I know what's on the plate I could say yes, it makes sense implemented it in the new one along with other code improvements 😁

**Comment by pkarw** [comment]
OK, I think we'll close it for now?

**Comment by lorenaramonda** [comment]
Could be closed if you don't forget it 😝 😇

**Comment by pkarw** [comment]
@filrak please put it on Your checklist please :)

**Comment by Igloczek** [comment]
Isn't better to keep it open and just add a proper label and milestone, rather than keeping it on some private "TO DO" list?

**Comment by pkarw** [comment]
@Igloczek @lorenaramonda no problem
