### ISSUE TITLE
[iPhone/Chrome] Mobile visuals

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#170]
1/ Margins
2/ Clicks - you have to click twice (1st click sets hover, second activates link which is counter-intuitive)
3/ Please do click each screen one by one using Dev. tools to see the site on mobile resolutions or using physical dev. or emulator 

We're going with public demo in next 2 weeks guys! :)

@filrak @mercs600 @patrykpiston who can take this one?

![3](https://user-images.githubusercontent.com/211899/32017818-397a6b02-b9c8-11e7-98fd-777b4bc9c9a9.png)
![2](https://user-images.githubusercontent.com/211899/32017819-399cdba6-b9c8-11e7-8bdf-c76cec76bbfc.png)
![1](https://user-images.githubusercontent.com/211899/32017820-39be8b48-b9c8-11e7-935b-6a1197f63f69.png)

**Comment by patrykpiston** [comment]
Recently had to fix this on another project, I can take this while working on #112 next week

**Comment by patrykpiston** [comment]
@filrak @mercs600 The double clicking on links on iOS is a tricky one for me. It's caused by the fact that apple products check if there is a hover effect, and then apply it on the first click.  

The only solutions I find online are just catching a click on any link and then manipulating the window.location with given link url. I think this would be too much interference with vue router though.

**Comment by mercs600** [comment]
@patrykpiston Double click is caused by pseudo element on href tag. We can just hide after pseudo element on mobile or use media query. It depends on browser support. At this moment should be ok. Look here https://github.com/mercs600/vue-storefront/commit/0c4fc5b0a05df7c078f0195aeb4bdb6f04886c68
