### ISSUE TITLE
Sale price is not shown on category page + product page

### ISSUE THREAD

**Issue by Esteraa** [DivanteLtd/vue-storefront#1972]
## Current behavior

1. Go to https://demo.vuestorefront.io/c/men-11
2. Check price first product
3. Click on first product
4. Go back to category
5. Sale price is shown on category page
6. Click on same product
7. Sale price is not shown on product page 

## Expected behavior

1. Show sale price on category page without clicking on the product first
2. Show sale price on product page

## Steps to reproduce the issue

![sale-price](https://user-images.githubusercontent.com/30499229/48198780-3de85c00-e35a-11e8-977c-3612eecba1a9.gif)

## Repository

https://demo.vuestorefront.io/c/men-11

# Can you handle fixing this bug by yourself?

No

**Comment by pkarw** [comment]
This is probably because we're not processing properly `product.configurable_children.price` either `product.configurable_children.special_price` in the list request. However the data is being progressively loaded on the product page - and thereof the special price (which in this case is assigned just to one of the `configurable_children`) start being available.

You can start by adding price fields to: https://github.com/DivanteLtd/vue-storefront/blob/dd25956818b5b5d2c6acf5937ec4022b66efa563/config/default.json#L121

Special price is assigned to the `32, Gray` - ONLY!

You should debug the `taxCalc.js` which is in charge of setting this price

**Comment by pkarw** [comment]
Fixed
