### ISSUE TITLE
New caching mechnism with config for product catalog

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#1994]
## What is the motivation for adding / enhancing this feature?

Right now our product caching mechnism cant be customized and we are unable to allow developers to use it's full power ;) since being fast and offline-ready is one  of our key values i believe we can have a neat caching mechanism that can be easly customised and adjusted to clients needs.

Few thigh that should be able to configure in such mechanism:
- do we want to cache whole category if product is viewed, if so is there any limit of SKUS or some criteria
- do we want to preload some of the categories right after user visits the page
- do we want to cache product images
- do we want to cache prices

# Can you complete this feature request by yourself?

Not before february. If you want take care of this before Feb feel free to grab the ticket and let's discuss it.

**Comment by thomasthune** [comment]
Seems like there are a couple of issues regarding the whole caching process in browser/service workers products. I'll comment on this one, since my pointers mostly can be boiled down to being able to configure the behavior of the app.

So basically on our current client site (running v. 1.4.1, though as far as i can see the behavior is the same for HEAD) We are experiencing some minor issues related to the product caching.
If a customer who has visited a product page revisits the page (directly), any updates to the products will not be shown. 
Just for a more concrete example:
One morning the customer visits a product page for a jacket.
During the day, the customer recieves a newsletter telling her/him that the jacket is now on sale.
When the customer visits the page following a direct link, the product page will be the same as it was in the morning, the product price will not be updated.

In order to see the correct price, the customer either has to navigate the page through the categories or the searchpanel (hoping not to match any of the previously cached searches). 

In our use case, we would want the customer (when online) to always get a fresh search request to elasticsearch. These results should be cached, as the are now, for use when offline.

**Comment by pkarw** [comment]
@thomasthune thanks for the feedback! We'll take it into consideration regarding new caching mechanism which is already scheduled + assigned: https://github.com/DivanteLtd/vue-storefront/issues/1990

ps. what's the address of Your site?
