### ISSUE TITLE
Improve the docker setup

### ISSUE THREAD

**Issue by DavidRouyer** [DivanteLtd/vue-storefront#2103]
## What are the acceptance criteria 
- Improve and fix the Docker setup by using muti-stage builds:
  - Use node-slim for building the application (we use native dependencies (node-sass) for example which requires Python and other dependencies)
  - Use node-alpine for running the app

- Explore #1845.

- Remove the shell script (not needed).

- Use a proper dev/prod setup.

# Can you complete this feature request by yourself?
YES

**Comment by dennisotugo** [comment]
Started work on this last year, almost done

**Comment by sandermangel** [comment]
Hi @dennisotugo did you manage to make any headway? :)

**Comment by tonyisworking** [comment]
Is there a need for the pm2 on docker? Seems better to go without and scale via docker instead of scaling via pm2 in a container. 

There's a discussion here about it on [stackoverflow](https://stackoverflow.com/questions/51191378/what-is-the-point-of-using-pm2-and-docker-together) and on [docker](https://www.docker.com/blog/keep-nodejs-rockin-in-docker/)

The current docker build isn't very cacheable and starts up slow. Moving the bind mounts into the image build works better, cacheable, and starts up faster. 

Also adding in a healthcheck seems like a thing too. Since there was no PR on this yet, I'm going to add one.
