### ISSUE TITLE
Category slug/links throws errors 

### ISSUE THREAD

**Issue by jorkvist** [DivanteLtd/vue-storefront#2205]
## Current behavior
Clicking a category gives an error message saying the category is not available in offline mode (im not offline). 

Settings:
      "useShortCatalogUrls": false,
      "useMagentoUrlKeys": false,
And "seo": { "useUrlDispatcher": false } (not sure what this one does)

When i check the request it says:
request: {“query”:{“bool”:{“filter”:{“bool”:{“must”:[{“terms”:{“slug”:[“fltlinor-47"]}},{“terms”:{“is_active”:[true]}}]}}}}}

But slug is not present and i don't get anything back.

## Expected behavior
Category should be loaded. 

## Repository
1.7

# Can you handle fixing this bug by yourself?
NO

## Environment details
- Browser: Chrome Latest
- OS: Mac OSX

**Comment by pkarw** [comment]
Dynamic Categories prefetching (#2076). Starting with Vue Storefront 1.7 we've added a configuration option config.entities.category.categoriesDynamicPrefetch (by default set to true). This option switches the way the category tree is being fetched. Previously we were fetching the full categories tree. In some cases it can generate even few MB of payload. Currently with this option in place we're pre-fetching the categories on demand while user is browsing the category tree

NOTE: Since we're no longer generating category.slug client's side - we need to have category.url_key field unique. If Your Magento2 url_keys are unique it will work without any changes. If not - please do use mage2vuestorefront to re-import the categories. There is a new categories importer option --generateUniqueUrlKeys which is set to true by default.

**Comment by pkarw** [comment]
https://github.com/DivanteLtd/vue-storefront/blob/master/docs/guide/upgrade-notes/README.md

**Comment by pkarw** [comment]
I think that in Your case the „categoriesDynamicPrefetch” need to be switched Off to maintain the previous behavior either You should reimport the products to set the url_key properly

**Comment by jorkvist** [comment]
I updated and tried to use useMagentoUrlKey=true. Issue now is that wrong category is matched. I have multiple categories with something like: "X", "AA-X", and "BB-X". When i click the link of "X" it loads category "AA-X". 

Seams like the issue is this one that is running when i click a category: 
{“query”:{“bool”:{“filter”:{“bool”:{“must”:[{“terms”:{“url_key”:[“X”]}},{“terms”:{“is_active”:[true]}}]}}}}}

The response here is a json answers for all of  "X", "AA-X", and "BB-X". Where "AA-X" is the first in the response, so it get shown as the category. Where another category is meant to be loaded.

**Comment by jorkvist** [comment]
Thanks! Changed this. Got it kind of working but opened another issue for the new issue.

**Comment by pkarw** [comment]
PLease use the latest vs-api - I've fixed this TOday at 8:00am :) You need to run `yarn db rebuil`
