### ISSUE TITLE
Improperly sum of Grand Total

### ISSUE THREAD

**Issue by ibugaj** [DivanteLtd/vue-storefront#2312]
## Current behavior
Wrong Grand total cost is in Cart
## Expected behavior
Grand total should be complied with prices of products added to Cart

## Steps to reproduce the issue
1. Add some product(s) to the Cart
2. Go to the Cart
3. See **Grand total**
Example:
![image](https://user-images.githubusercontent.com/47220013/52074588-80e95280-258a-11e9-84e9-03fc08e0c268.png)

## Environment details
https://demo.storefrontcloud.io/
- Browser: Google Chrome
Wersja 71.0.3578.98 (Oficjalna wersja) (64-bitowa

## Additional information
This issue appears independently if you add one or few products to the Cart. 
I tried count it in different ways, but in no case does the amount disagree

**Comment by filrak** [comment]
@pkarw sth related to server side totals calc?

**Comment by pkarw** [comment]
This is done on Magento side; it’s not a VS issue (probably magento either - I mean it’s correct value - because of discount, taxes and other things magento is summing up); usability isn’t great - I totally agree with that haha :-)

 One can configure how totals look like in magento2 admin. So I’m closing this one as it’s not an issue to be fixed in VS :)
