### ISSUE TITLE
selection checkbox for receiving Newsletter isn't saved

### ISSUE THREAD

**Issue by ibugaj** [DivanteLtd/vue-storefront#2364]
## Current behavior
Selection checkbox for receiving Newsletter isn't saved
## Expected behavior
Selection checkbox for Newsletter should be saved
## Steps to reproduce the issue
1. Be a logged user
2. Go to My account - My Newsletter
3. Click on **Edit newsletter preferences**
4. Select checkbox **I want to receive a Newsletter, and agree to its terms**
5. Click on **Update my preferences** button
6. Go to another page, for example **My orders** and back to **My newsletter**

## Environment details
https://test.storefrontcloud.io/

## Additional information
When user proceed steps 1-5 and then refresh page, then he will redirected on Home page with notification **You need to be logged in to see this page** (but user still stayed logged)

![image](https://user-images.githubusercontent.com/47220013/52235717-3be45980-28c5-11e9-84e6-e2ea75242221.png)

**Comment by vue-kacper** [comment]
Reload of any "My account" section page (as authenticated user) redirects to home with this notification. I think it's related to SSR "My account" pages reload logic for unauthenticated user. 

We've introduced it a while ago to redirect unauthenticated users from "My account" to "Homepage" on reload.

Maybe we should not redirect user at all in this scenario because we can't detect if user is authenticated on SSR

**Comment by pkarw** [comment]
@filrak I know that You were working on both: route guards + newsletter refactoring; can you check this one please?

**Comment by filrak** [comment]
already spoke with @vue-kacper about it. he si gonna take care of this

**Comment by pkarw** [comment]
Related to #2754
