### ISSUE TITLE
Wrong price flashing briefly when loading bundle product page

### ISSUE THREAD

**Issue by jeremycharron** [DivanteLtd/vue-storefront#2371]
## Current behavior
A wrong price is flashing briefly when loading/reloading a bundle product page.

## Expected behavior
The right price should be showed right from the start **OR** the price should be hidden while loading

## Steps to reproduce the issue
1. Go on any bundle product page
2. Reload the page
3. Look for the price flashing for about 1 second

## Environment details
https://demo.vuestorefront.io/p/24-WG080/sprite-yoga-companion-kit

**Comment by patzick** [comment]
Thanks for issue. That behaviour is caused by setting default values on component mounted lifecycle, so after its rendered.

![image](https://user-images.githubusercontent.com/13100280/52324714-b0f98100-29e2-11e9-9c13-f90dfea5f80a.png)

Although you haven't filled info if you're willing to improve it by yourself.
It's nice case for first issue:)

**Comment by pkarw** [comment]
It was an issue with `setupAssociated` called 2 times
