### ISSUE TITLE
Password Reset response undefined

### ISSUE THREAD

**Issue by revlis-x** [DivanteLtd/vue-storefront#2378]
## Current behavior
When clicking reset password in the modal dialog, the api-call gets made correctly, returns correct payload and email is sent, but console error appears "response is undefined" and because of that the UI never gets updated to ""passworsSent"-State.

## Expected behavior
Response gets passed back to ForgotPass.vue correctly, so that UI can respond to it.

## Steps to reproduce the issue
1. Fill email and click reset password
2. Look in browser console

# Can you handle fixing this bug by yourself?
Unfortunately not.

## Environment details
https://demo.storefrontcloud.io/

**Comment by patzick** [comment]
Hey @revlis-x 
i think this is fixed in current develop
I get this:
![image](https://user-images.githubusercontent.com/13100280/52360244-dc5c8a00-2a3b-11e9-88e0-bc98d70467c0.png)

Or if magento limit is reached this:
![image](https://user-images.githubusercontent.com/13100280/52360355-188fea80-2a3c-11e9-98d4-bd75f877f4c9.png)

Please check if you can reproduce this in https://test.storefrontcloud.io and reopen this issue if so.
