### ISSUE TITLE
User can add the same email address many times for subscribing

### ISSUE THREAD

**Issue by ibugaj** [DivanteLtd/vue-storefront#2459]
## Current behavior
User can add the same email address many times for subscribing
## Expected behavior
Notification, that email address has been added to subscribe before (because, I guess, that discount should be allowed only once time for the same address)
## Steps to reproduce the issue
1. Scroll down page to **Subscribe to the newsletter** section
2, Click on Subscribe button
3. On modal fill field by any email addressand click Subcribe
4. Repeat steps 2-3 (fill with the same email address)

## Environment details
https://test.storefrontcloud.io/

**Comment by filrak** [comment]
i guess the mailchimp module is not working anyway @pkarw ?

**Comment by pkarw** [comment]
This behavior was intentional - we should just display some message from Mailchimp in case of re-entry or we can save the state to localStorage probably. This is not the Magento newsletter integration intentionally. I belive it should be saved in localStorage + we should handle the error message from mailchimp and that's all :)

**Comment by pkarw** [comment]
Related to #2754

**Comment by janmyszkier** [comment]
and possibly #1899
