### ISSUE TITLE
Two the same categories on Search page

### ISSUE THREAD

**Issue by ibugaj** [DivanteLtd/vue-storefront#2460]
## Current behavior
Two the same categories on Search page (with the same results of searching)

![image](https://user-images.githubusercontent.com/47220013/53048648-85bc6a80-3495-11e9-827c-e756d4107a26.png)

![image](https://user-images.githubusercontent.com/47220013/53048574-5e659d80-3495-11e9-8d90-97c41faaed72.png)
 
## Expected behavior
There should be difference for names of categories or doesn't display two categorie with the same name and results

## Steps to reproduce the issue
1. Open Search page (click on loupe)
2. Enter any phrase to get results, for exmaple: _top_
3. See on **Filter by categories**

## Environment details
https://test.storefrontcloud.io/

## Additional information
For another phrase, for exmaple: _t-shirt_, there are also two categories with the same name (Shorts), but when you choose one or the other, then you will see that one is for men and another for women.
![image](https://user-images.githubusercontent.com/47220013/53048241-9a4c3300-3494-11e9-90b6-53303cba5131.png)

![image](https://user-images.githubusercontent.com/47220013/53048287-b059f380-3494-11e9-84db-5da8bbc0701a.png)

BUT, in first case, there is no difference between these two category results

**Comment by cnviradiya** [comment]
@ibugaj I also noticed this but as I debug this issue there are two categories exists in Magento sample data that's why Here you can see two times same category. Due to same product in two same name categories.
Look at below screenshots for better understanding.

![screenshot-demo-magento2 vuestorefront io-2019 03 06-16-07-47](https://user-images.githubusercontent.com/9442993/53875311-41e76a80-402a-11e9-8230-127d84b6dd38.png)
![screenshot-demo-magento2 vuestorefront io-2019 03 06-16-08-31](https://user-images.githubusercontent.com/9442993/53875319-457af180-402a-11e9-98cc-338310f89ab4.png)

**Comment by pmaojo** [comment]
This is still an issue.
![Captura de pantalla 2019-06-04 a las 20 21 53](https://user-images.githubusercontent.com/411551/58907736-c53a5a00-8706-11e9-870b-178c3e7ceaf0.png)

It is obvious that there are repeated names becouse those categories exist, being children of different parent caregories. 

It could be a good thing to come up with a solution that provides the user more info (displaying parent categories or merging similar tags into one)

**Comment by pmaojo** [comment]
@pkarw 
What do you think?
