### ISSUE TITLE
Microcart count on prod

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#247]
After last PR https://www.dropbox.com/s/x3zjgd7jmidfppw/Zrzut%20ekranu%202017-11-06%2019.11.33.png?dl=0

**Comment by karolbzik** [comment]
Here are my suggestion to the adjustments of the top.

Current state on the desktop/tablet:
![zrzut ekranu 2017-11-06 o 22 24 59](https://user-images.githubusercontent.com/18116406/32464759-60396dba-c341-11e7-8861-6e78be22b4c4.png)
![zrzut ekranu 2017-11-06 o 22 25 08](https://user-images.githubusercontent.com/18116406/32464766-62eecf82-c341-11e7-9c56-f08593307796.png)

Desired state on the desktop/tablet:
![zrzut ekranu 2017-11-06 o 22 23 06](https://user-images.githubusercontent.com/18116406/32464670-18f0327c-c341-11e7-9b69-c02b66616bf4.png)
Changes:
- Styles stay the same for desktop and tablet, optionally we can remove from the top "search" button and "saved" button
- Add the background color to the menu button

Current state on the mobile:
![17](https://user-images.githubusercontent.com/18116406/32464580-d07cbba0-c340-11e7-988c-4012bd10c331.png)

Desired state on the mobile:
![zrzut ekranu 2017-11-06 o 22 21 38](https://user-images.githubusercontent.com/18116406/32464613-e47dc90a-c340-11e7-82bd-94304c204eb9.png)
Changes:
- only sidebar cart and sidebar menu
- sidebar menu button with the background

**Comment by patrykpiston** [comment]
@filrak again, the same thing happened to the icons here.

I'm not sure why but, unless specified by atomic classes, the style isn't applied. It may be due to the fact the microcart count was missing the lang="scss" tag, however I don't see how that would affect scoped styles. This seems to be a problem only with MicrocartIcon.vue for some reason. Odd.

Below are screens of the element in question, first is the good one, styles applied, the latter is the prod, without styling.

![good](https://user-images.githubusercontent.com/23720398/32478250-0342b254-c384-11e7-9171-fbcdd97f70bd.png)

![bad](https://user-images.githubusercontent.com/23720398/32478259-0925f046-c384-11e7-8256-30bd882640ce.png)
