### ISSUE TITLE
[docs] remove theme-starter references

### ISSUE THREAD

**Issue by janmyszkier** [DivanteLtd/vue-storefront#2538]
on https://docs.vuestorefront.io/guide/core-themes/themes.html there are still refrences to theme-starter that was removed in 1.6.0. 
Either reintroduce the starter or change to docs to copy the default theme instead.

**Comment by janmyszkier** [comment]
@filrak can you let me know which one you prefer to do? if that's just a doc update I can do this.

**Comment by coccoinomane** [comment]
Hi there!
I have sent a pull request for review in which I have removed the `theme-starter` references from the docs.
I did so because at the moment it is a bit confusing having the docs referr to a non-existent folder in the codebase.
I hope that helps, otherwise please feel free to close the PR.
Cheers,
Guido
