### ISSUE TITLE
Thumbnail images of products in View order

### ISSUE THREAD

**Issue by ibugaj** [DivanteLtd/vue-storefront#2544]
## What is the motivation for adding / enhancing this feature?
Clear view of preview for my orders

## What are the acceptance criteria 
For logged users, in My Orders tab, view order could show thumbnail images of product - it will be more clear for user, what he has added

## Additional information
New column for thumbnail in table

![image](https://user-images.githubusercontent.com/47220013/53748534-c9f03780-3ea5-11e9-949f-0b8f048e92a9.png)

**Comment by awierzbiak** [comment]
Working on it.

**Comment by Hackbard** [comment]
Any news @awierzbiak ?

**Comment by awierzbiak** [comment]
Sorry, didn't have time to finish this one 😞

**Comment by patzick** [comment]
Thanks, @obsceniczny! Ready for QA tests :)

**Comment by ArturDivante** [comment]
Hello! @obsceniczny @patzick - Function works nice &fine with one exception - for bundle product it returns placeholder instead of actual picture. Can we fix that easy, or is it more complex? 
![bundle](https://user-images.githubusercontent.com/47415585/64540725-e8d1f980-d320-11e9-98cc-572efacdfcce.png)

**Comment by patzick** [comment]
@obsceniczny would you mind to take a look? :)
