### ISSUE TITLE
Multiple browser tab mutation sharing

### ISSUE THREAD

**Issue by BartoszLiburski** [DivanteLtd/vue-storefront#2549]
We don't have any mutation sharing system, so add to card, logout, add to wishlist etc. wont appear on every tab (if more than one opened). 
My idea is to add some hook like afretRegistration and fire up storeDispatch like here: https://github.com/DivanteLtd/vue-storefront/pull/2547

Other option is to use: https://www.npmjs.com/package/vuex-shared-mutations

**Comment by patzick** [comment]
My question is - is it only about mutations sharing?
As i understood initiative was that that items added to cart in first tab was not visible on second tab. Then yes - shared mutation solves that issue.
But we have many mutations, even opening side menu, show overlay or set current category. Sharing mutations could cause unexpected behaviours on other tabs, really hard to debug also.

But i would like to look deeper. For example someone would like to show some info when user switch to tab, or send a request to API to check if user session is still valid and log out if not, or refresh cart. Then simple sharing mutations is not enough (also user can switch from tab which was not our application).

In this case my vote is for creating a reactive helper like `onlineHelper`. And if we need - we can watch helper state and even create hook if needed in future.
Example of helper:

```js
// Tab activity helper
export const visibilityHelper = Vue.observable({ 
  isTabVisible: isServer || document.visibilityState === "visible"
})
!isServer && window.addEventListener('online',  () => visibilityHelper.isTabVisible = document.visibilityState === "visible")
```

Additional info: doc recommends to use visibilityState instead of document.hidden (https://www.w3.org/TR/page-visibility/#hidden-attribute)

**Comment by pkarw** [comment]
This has been fixed by adding the `cart/load` on tab switching already
