### ISSUE TITLE
Seo friendly urls - bugs

### ISSUE THREAD

**Issue by afirlejczyk** [DivanteLtd/vue-storefront#2598]
## Current behavior

1. If I disable seo URL I have different category link in the menu and in breadcrumbs.
In breadcrumbs, I have the correct link with 'c' prefix
In menu I don't have it "c" prefix -> URL is still generated base on 'full_path'

2. If I go directly to subcategory page
https://next.storefrontcloud.io/men/tops-men/jackets-men/jackets-14
I don't see full menu -> maybe it is connected to the first issue.

## Expected behavior

1. Regardless of new config setting: `seo.useUrlDispatcher`, we should always get the same URL for the category in the menu and in breadcrumbs.

## Steps to reproduce the issue

1. set `seo.useUrlDispatcher` to false I check category URL in the menu and in breadcrumbs

## Can you handle fixing this bug by yourself?

NO

**Comment by pkarw** [comment]
I’m not sure when I’ll be able to fix this one so @patzick and @filrak just feel free to take care of it :)

The second one: we should use `formatCategoryLink` instead of localizedRoute in both: Sidebar and Breadcrumbs.

The first one: on the other pages the “category/load” is called with the root category level as a filter. In product and category pages by some reason it’s called just for the categories on the breadcrumb path. Something is probably wrong with how breadcrumbs are loaded (?). 1.8.4 works just fine so it must be somehow related to url dispatcher
