### ISSUE TITLE
yarn installer script dependencies are missing

### ISSUE THREAD

**Issue by saitam1** [DivanteLtd/vue-storefront#2829]
I am running: Ubuntu `18.10`, yarn `1.15.2`, node `9.11.2`
After following the docs:
```
git clone https://github.com/DivanteLtd/vue-storefront.git vue-storefront
cd vue-storefront
yarn
yarn installer
```
I get several errors from this:

1. Cannot find module 'shelljs'. 
I looked it up and it is in `vue-storefront/node_modules/pm2/node_modules/shelljs` but not in `vue-storefront/node_modules`, so I installed it globally, which helped. 

2. Cannot find module 'fs-exists-sync'.
I looked it up, its not there. So I installed it globally AND locally, but still the same error! Where is vue-storefront installer script looking for it?

**Comment by pkarw** [comment]
@lukeromanowicz could You please check this one on clean install?

**Comment by lukeromanowicz** [comment]
@saitam1 I've tested it on Ubuntu 18.04 with an exact version of yarn and nodejs and everything passed without any errors. Is your yarn.lock modified compared to the one in the repository? Do you have enough space on your hard drive to store the whole node_modules directory? Could you try running vue storefront in docker instead of locally and let us know if it works?
