### ISSUE TITLE
Special price is 0

### ISSUE THREAD

**Issue by glevhen** [DivanteLtd/vue-storefront#2838]
## Current behavior
The special price of the product is 0
![image](https://user-images.githubusercontent.com/16398798/56949812-854aea80-6b3c-11e9-991e-6a15ba651c6b.png)

## Expected behavior
Special price should contain value from product configurations

## Steps to reproduce the issue
1) open product configurations in the Magento admin dashboard, set special price to the product 
![image](https://user-images.githubusercontent.com/16398798/56950499-533a8800-6b3e-11e9-985d-c9d485d75630.png)

2) rerun vs-api synchronization
3) check the product price on the vs frontend 
the special_price is 0, but special_from_date is correct
![image](https://user-images.githubusercontent.com/16398798/56950642-a14f8b80-6b3e-11e9-8594-fd10f346291b.png)

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Google Chrome
- OS: macOS Mojave
- Node: v8.15.0
- Code Version: master branch, commit hash - 76acad7fa90df6c1e53dd6d4245b42a0cbe47968

**Comment by pkarw** [comment]
Hi @glevhen have You synchronized the products after setting the `special_price`? 
The `special_price:
- is checked and can be set to 0 in `vs-api` - https://github.com/DivanteLtd/vue-storefront-api/blob/master/src/lib/taxcalc.js
- maybe it's just not synchronized correctly - this option should be set to `true` in order to have it synchronized: https://github.com/DivanteLtd/mage2vuestorefront/blob/c71788e1c918225685344657f9d6ca0b2417d801/src/config.js#L44


@kkdg maybe it's something that need to be updated in the docs as well?

**Comment by glevhen** [comment]
@pkarw, we synced products after setting special price
and option is true in the config 
![image](https://user-images.githubusercontent.com/16398798/56954217-ee376000-6b46-11e9-866c-47688318d2eb.png)

**Comment by pkarw** [comment]
Please try out to set RENDER_PRICES to true as well and let me know about the result

**Comment by glevhen** [comment]
@pkarw changed the settings, synced products again, but special_price still is 0
![image](https://user-images.githubusercontent.com/16398798/56954901-aca7b480-6b48-11e9-9917-488697e5d13c.png)

**Comment by pkarw** [comment]
How do you run the indexer?
You might want also to check the native indexer: https://github.com/DivanteLtd/magento2-vsbridge-indexer

**Comment by pkarw** [comment]
Please also do check if special_price is 0 in elastic search (for example using Es-head Chrome plugin or Kibana) or please do send us the catalog.json datadump of Your elastic after import (yarn dump)

**Comment by pkarw** [comment]
@glevhen there was indeed a logic error (basically it was more like date conversion error) - fixed with https://github.com/DivanteLtd/vue-storefront-api/commit/64c8f0d55a6dd0b0409e17b243c97feb9ca845fa to `vue-storeferont-api`. Please do update Your API. The products probably don't need to be re-synced.
