### ISSUE TITLE
Incorrect value in PRAPI, when quantity is >1 

### ISSUE THREAD

**Issue by ArturDivante** [DivanteLtd/vue-storefront#2874]
## Current behavior
Summary during 'Instant checkout' displays only single product price - even when quantity was set diffrently.  Other values (shipping, grand total) are displayed correctly. 

Customer sees group of quotas and grand total, that does not match.   

![PRAPI](https://user-images.githubusercontent.com/47415585/57383030-5cff6380-71ae-11e9-9f2f-3ad33901ab1b.PNG)

## Expected behavior
Value displayed along with product name, should be calculated basen on quantity. 

## Steps to reproduce the issue
1. Add any product to cart **with quantity > 1**
2. Proceed t Instant checkout
3. Check displayd summary

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome
- OS:  Win10

**Comment by GabiDivante** [comment]
Hi @pkarw @ArturDivante @vishal-7037
I was testing this fix and I think that maybe we need a more complex solution.
There are two more situations where prices visible in the Instant Checkout Order summary are still different than in the cart, so again the customer sees a group of amounts and grand total, that does not match:

**1. When an item has a reduced price due to some cart discount rule or discount code added.**

In this situation, the 'Discount' line appears and the full prices of the listed products are visible in the Instant Checkout summary. 
For now 'Discount' shows value only from the net price without tax, so the discount of the tax is missing, to have the correct equation.


So we can solve this in two ways:
a. show reduced prices and hide discount line
b. show correct discount value (with tax)

_Look out for reduced price in the cart (currently not correct calculation - #2892)._

**2. When customer provided in his Shipping Details a country for which the tax is not included.**

The prices without tax are visible in the cart, but in Instant Checkout summary customer sees the full prices with the tax.

**Comment by GabiDivante** [comment]
1. 
![Selection_030](https://user-images.githubusercontent.com/49188852/57623029-2c913e00-758f-11e9-83e1-a58dfb4bc4bd.png)

**Comment by GabiDivante** [comment]
2. 
![Selection_032](https://user-images.githubusercontent.com/49188852/57623255-b3deb180-758f-11e9-981e-225227a72d8e.png)

**Comment by GabiDivante** [comment]
https://drive.google.com/file/d/16wo3fCXzgEIMJ-8RXnIuebO2fQ7Decve/view?usp=sharing

**Comment by GabiDivante** [comment]
@qiqqq @patzick @pkarw 
I tested changes on next and something is wrong again. 
When I apply a discount code (mmtest - 50%) -> price visible next to the product is correct (it contains tax already) but in the Instant Checkout, the product price has tax value doubled. 
Maybe this fix #2892 has not been taken into account. 
We should show the same reduced price in the instant checkout as in the cart. 
![Peek 2019-06-18 10-50](https://user-images.githubusercontent.com/49188852/59668017-0aa36080-91b8-11e9-8a29-043bc6b357d7.gif)

**Comment by pkarw** [comment]
Fixed
