### ISSUE TITLE
Configurable Products not accessible in CSR when children visibility is set to "not visible individually"

### ISSUE THREAD

**Issue by revlis-x** [DivanteLtd/vue-storefront#2933]
## Current behavior
In 1.9 one cannot access Configurable Products in CSR (e.g. clicked from category listing), when the visibility of the children is set to "not visible individually" in Magento. Instead one is redirected to Homepage with error message.
For further details view this slack thread: https://vuestorefront.slack.com/archives/CA68P1JUF/p1557923071162700

## Expected behavior
This was working in versions before 1.9

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Additional information
I will provide a PR with a fix.

**Comment by pkarw** [comment]
Could You please paste the info form Slack into comments to avoid the risk of Slack removing the history due to messages limit (we're on free version)?

**Comment by Jensderond** [comment]
yogeshsuhagiya   [7 days ago]
I'm also facing the same issue after upgrading VS version

ZigaBBS   [7 days ago]
Me too, maybe it is problem in default.json config file, im setting it up now will report when i test

yogeshsuhagiya   [7 days ago]
@ZigaBBS Don't think so, there is something wrong with core code.

yogeshsuhagiya   [7 days ago]
VSF team developed and used `RouterManager`, might be this will be the reason.

yogeshsuhagiya   [7 days ago]
They replaced
`import routes from './router'`
with
`import { RouterManager } from '@vue-storefront/core/lib/router-manager'` (edited)

Jens   [7 days ago]
This is no problem, I suggest copying the latest default.json to local.json so you don’t forget anything.

Jens   [7 days ago]
As the default file has changed a bit, see: https://github.com/DivanteLtd/vue-storefront/commit/be5d10d183de9a257a68251828c07ca2161290f4#diff-1e9c3d615e9ebaaaa3669b4c2fd87d00 (edited)

Jens   [7 days ago]
And:
https://github.com/DivanteLtd/vue-storefront/commit/93949bc70bc3a1303500815b71b49d1fc98ba3f6#diff-1e9c3d615e9ebaaaa3669b4c2fd87d00

reVLis   [7 days ago]
I'm just in the process of upgrading to 1.9 and experiencing the same issue: configurable products do not load in csr when clicked from category page....same url is working in SSR though...urlDispatcher is set to false.  I will start investigating and any help is welcome :smile: (edited)

yogeshsuhagiya   [7 days ago]
@Jens I've added all latest changes of `default.json` file into `local.json` file but still issue is there

ZigaBBS   [7 days ago]
Same...

pkarw (Core Team)   [7 days ago]
please reindex the products with the latest version of mage2vs then run the `yarn db rebuild` in the `vs-api` and make sure the product.url and category.url fields are set in the Elasticsearch - if so, it should work jsut fine

pkarw (Core Team)   [7 days ago]
You can also set config.useUrlDispatcher = false in order to have the backward compatibility

pkarw (Core Team)   [7 days ago]
@degi - working on cookbook this is something that we probably emphasise in the docs -> I mean runing the `yarn db rebuild` after importin the products / upgrading to 1.9 as the `url_path` has `keyword`  data type and won’t work on defualt string

Mateus Nunes   [6 days ago]
@pkarw (Core Team)  i had the same problem that @Jailson Dias  was describing, the funny thing is: on the vsf If im on the home page And click on the product the CSM error do pop up, but If go direct link ( open a new tab And paste the product URL ) It works Just fine, show the product without any errors, If you have any ideia on How to fix this or any clue on what might be happening please let me know here

reVLis   [6 days ago]
I still could not pinpoint the issue. Regardless if using UrlDispatcher or not: SSR is working for all products, CSR is working for all products when clicked FROM SEARCH. CSR is working for SImple Products when clicked from category. CSR is not working for nearly all configurable products from category - though i have a handful of configurable products that do work - could not make out any difference....definately something funky going on here (edited)

yogeshsuhagiya   [6 days ago]
@reVLis I got the solution, DM me

Jens   [6 days ago]
@yogeshsuhagiya Could you share the solution in form of a PR maybe?

yogeshsuhagiya   [6 days ago]
@Jens
*Step 1:* Open `vue-storefront/core/modules/catalog/store/product/actions.ts`
*Step 2:* Goto line number 601 in `fetch` method
*Step 3:* Find following code inside `fetch` method
``
if (product.visibility === 1) { // not visible individually (https://magento.stackexchange.com/questions/171584/magento-2-table-name-for-product-visibility)
       throw new Error(`Product query returned empty result product visibility = ${product.visibility}`)
     }
```
*Step 4:* Comment out that code or just remove it

*Note: It's no a genuine solution, it's only temporary fix* (edited)

reVLis   [6 days ago]
This works with the side-effect of having configurable children accessible via url

Jens   [6 days ago]
@yogeshsuhagiya Could you please make a GH issue describing your problem, with this temporary solution for others experiencing the same? I’m not experiencing it so I don’t think I could make it clear enough

reVLis   [6 days ago]
In short: one cannot access configurable products when the visibility of the configurable children is set to "not visible individually" in magento (edited)

yogeshsuhagiya   [6 days ago]
@Jens I think it will be hopefully fix in new release of VSF and some issues are already there in GH relate to this issue

reVLis   [6 days ago]
@yogeshsuhagiya can you share which GH-issues that are? Because else I will create one for this specific problem to raise awareness...

yogeshsuhagiya   [6 days ago]
@reVLis can you please open a GH issue?

reVLis   [6 days ago]
Will do

pkarw (Core Team)   [6 days ago]
@reVLis this issue occurs when just >one< of the configurable_children is not visible, correct?

pkarw (Core Team)   [6 days ago]
very valuable insights, thanks Guys!

pkarw (Core Team)   [6 days ago]
Please do create an issue or even beter - aPR with a fix :smile: I belive it may be caused by merging the configurable_children with the current product >before< checking it status - i mean `product/configure` or `cofnigureProductAsync` helper is being called from the `product/list`https://github.com/DivanteLtd/vue-storefront/blob/2646de2905174c4d20c6f3365769b0a90cef353a/core/modules/catalog/store/product/actions.ts#L309
core/modules/catalog/store/product/actions.ts:309
            ```let selectedVariant = configureProductAsync(context, { product: product, configuration: configuration, selectDefaultVariant: false })```
DivanteLtd/vue-storefrontAdded by GitHub

pkarw (Core Team)   [6 days ago]
I think that we could check all the configurable_children visibiltiy before this line (309) and then set the `product.visibility` like a kind of `max(product.visibility, configurable_children.visibility)` - which will disable the product ONLY when all the configurable_children + the product itself are not visible (edited)

pkarw (Core Team)   [6 days ago]
However, the issue @Mateus Nunes described can be caused by the other reason - both SSR and CSR (browser) modes must have the access to the `config.elasticsearch.host` address. Would be great to ahve a Feature request to add a proper error message in case is not accessible (currently we don’t have any error message in a case of Ealsticsearch not accessible)

reVLis   [6 days ago]
If we just do not overwrite Parent-Visibility with Child visibility on line 309, then everything should work fine!? I think visibility of the configurable should be derived only from itself and not any children
e.g. :
```let selectedVariant = configureProductAsync(context, { product: product, configuration: configuration, selectDefaultVariant: false })
delete selectedVariant['visibility']
Object.assign(product, selectedVariant)```
(edited)

pkarw (Core Team)   [6 days ago]
OK, I belive it’s better to use the `omit`

pkarw (Core Team)   [6 days ago]
like in here: https://github.com/DivanteLtd/vue-storefront/blob/2646de2905174c4d20c6f3365769b0a90cef353a/core/pages/Product.js#L173
core/pages/Product.js:173
        ```this.$store.dispatch('product/setCurrent', omit(product, ['name']))```
DivanteLtd/vue-storefrontAdded by GitHub

pkarw (Core Team)   [6 days ago]
Could You please propose a PR for that?

reVLis   [6 days ago]
Will do...it's hotfix stuff for 1.9.1, right?

pkarw (Core Team)   [6 days ago]
Yeah, sounds like a hotfix

pkarw (Core Team)   [6 days ago]
Thanks man!

**Comment by patzick** [comment]
Thanks @revlis-x !

**Comment by cewald** [comment]
Just for the records and backlinks I had this problem described in the forum too (the fix works):
https://forum.vuestorefront.io/t/product-links-route-to-home-with-offline-message/296
