### ISSUE TITLE
on Refresh, language is set back to default language. 

### ISSUE THREAD

**Issue by thomsonsebastian** [DivanteLtd/vue-storefront#2976]
The language is changed to the default language on refresh. I have followed the steps below.

Steps:
1. when logged in to the site, language is set to 'de-DE' using loadLanguageAsync(language).
2. logged out from the site.
3. log in to the site again, language is set to 'de-DE' as usual.
4. refresh the site. the language is changed from 'de-DE' to 'en-US' (the default language)

**Comment by pkarw** [comment]
Hi! Thanks for the feedback. VS sets the language based on the urls (/de, /it prefixes) or the http header / env variables etc. it doesn’t currently saves the language per user / browser. So I’m not sure if this is a bug but rather kind of feature request maybe?

Can You please describe Your desired behavior of VS core in this case? I mean You probably added some custom code or config to change the language based on user preferences (?) I’m just guessing based on the description. Any way - by default the Lang is not bound to the user profile

**Comment by gopkumargopi** [comment]
@pkarw If VS has multiple languages per store, and I assume it has, it should be changeable on after logged-in events somewhere right?

e.g. we have a single store setup i.e. `"multistore": false`, lets say we have set two locales as `"availableLocale": ["en-US","de-DE"]`. When we refresh the page, immediately after the authentication can't we just switch the language to one of the available ones rather than VS core switching to the default?

This would enable custom themes to have control on the locale preferred by the user.

NOTE: This was possible in early stages I think at v1.10 to be exact.

**Comment by pkarw** [comment]
Ok, so I belive it’s still possible to just switch the i18n. Take the multistore.ta: prepareStoreView as a reference. Seemingly VS is calling it with default store view by the SSR reload. It doesn’t look like a bug - you can always programmatically overrode the current i18n just after page reload from the theme or module level. If you meant to add some core feature for that please let us know how exactly you’d like to have it or please draft a Pull Request
