### ISSUE TITLE
Possible to use woo commerce as backend?

### ISSUE THREAD

**Issue by negati-ve** [DivanteLtd/vue-storefront#307]
Hi,
First of, 
Really appreciate the effort put into building this project!

Since vue-storefront is platform agnostic, has anyone tried using woo commerce as a backend ?

I have a bunch of stores on woo and would like to see how vue-storefront can be integrated to the same..

Thanks, 
Any help in the direction is appreciated!

**Comment by pkarw** [comment]
Thanks for good words :) As far as I know nobody tested woocommerce yet. But to be honest it's quite simple to add support for it. Please take a look at: https://github.com/DivanteLtd/mage2nosql

What need to be done is to create another adapter like `woocommerce` similiary how magento adapter has been built: https://github.com/DivanteLtd/mage2nosql/tree/master/src/adapters/magento

So you need to adapt the data from DB or API to the current data formats in Elastic Search

And that's all :) The data formats are quite simple, some of them you can see here: https://github.com/DivanteLtd/vue-storefront/blob/master/doc/ElasticSearch%20data%20formats.md (it's not current, need to be updated)

The most fresh data formats are available in demo data dump: https://github.com/DivanteLtd/vue-storefront-api/blob/master/var/catalog.json

**Comment by negati-ve** [comment]
Thanks @pkarw ! 

Will be going through your links now and will update the progress here.

**Comment by pkarw** [comment]
Hi there! Any updates? Do you need any help @negati-ve?

**Comment by DesignNG** [comment]
@pkarw - Did this ever get done?

**Comment by pkarw** [comment]
@DesignNG I haven't hear anything on that :/

**Comment by DesignNG** [comment]
@pkarw Considering Builtwith stats show that WooCommerce powers 42% of all online stores worldwide, compared to Magento at 4%, surely it would make sense to offer that functionality out of the box as you do for Magento?

<img style="max-width:100%;" alt="screen shot 2018-04-25 at 11 28 03" src="https://user-images.githubusercontent.com/38355633/39240494-d7188a28-487b-11e8-9c1c-f42e8238acfc.png">

**Comment by ablears** [comment]
Are there any Woo adapters yet?

**Comment by NilsITO** [comment]
As well looking for woocommerce functionality

**Comment by amenadiel** [comment]
@DesignNG I totally agree there should be an adapter for Woocommerce.

However, I don't know where did you pull those stats from.

Currently these are the stats on builtwith

![ecommerce](https://user-images.githubusercontent.com/238439/45931802-63a3d800-bf49-11e8-9d59-890bd153ee76.png)
If you use "whole internet" instead of "top 1M" shopify turns out to be the most used one. It's also good to note that woocommerce is present in a lot of sites that doesn't have a functional checkout. This piegraph shows only sites that use woocommerce for ecommerce purposed and not, for example, displaying a catalog of phone specs like, say, gsmarena.

**Comment by phronesis** [comment]
I want to work on this, starting this week, who else is available to join?

**Comment by pkarw** [comment]
@phronesis we're starting currently some PoC project for this integration - currently it's to early to involve more ppl. We'll contact You in next 2-3 weeks regarding this integration

**Comment by phronesis** [comment]
I already started work on this yesterday. Some of my thoughts around this
include:

1. Building a data bridge, similar to
https://github.com/DivanteLtd/pimcore2vuestorefront . The purpose of this
will be one-time dumps from woocommerce to Elasticsearch.
2. Then work on a wordpress/woocommerce plugin that will push to elastic
search once a new product is created or edited on woocommerce
3. Then will need to add a platform for woocommerce to vue-storefront-api
that can handle things like stock sync, order to woocommerce, like “order
to magento” and all that bit.

Thinking of using Woocommerce nodejs client more like
this: github:DivanteLtd/magento2-rest-client is used to interact with
Magento 2.

Will love to be a part of the PoC project

**Comment by pkarw** [comment]
OK! Please do share Your output whenever You're ready

**Comment by koftkoft** [comment]
My team has experienced in digging deepest to Woo Commerce code,  several things are different from Magento's view.

Woo doesn't have cart API (can be added with a plugin but not official one), I'm not sure does it required in VueStoreFront to use it since i'm very new to this but really interest in plugging it into Woo. They use order API and rely that the client will manage and update it in a correct way. Using an API Gateway can help this too.

Woo have a plugin named ElastricPress which do update/sync data to ElastricSearch DB already, which they are very good and we can adapt hook/action from them.

By the way, when coming into a multi-language store the load of new problems will be introduced at that time, not all plugin working peacefully together.


We are starting to work on this too,  Cheers !!  @phronesis @pkarw

**Comment by pkarw** [comment]
@koftkoft awesome! Let me know if You require any help

**Comment by jonlee90** [comment]
Hey guys! 
I was wondering what the progress is for the woocommerce adapter and if you guys need any help on this.

**Comment by phronesis** [comment]
Hi @jonlee90, was on a vacation last week. Started preliminary work on the extension by following the procedure outlined here: https://github.com/DivanteLtd/vue-storefront-integration-boilerplate. Will share the link to the repo where I'll be pushing the source code to, so I could get early feedback.
By Friday this week, I should have something substantial.

**Comment by PatrickKluwig** [comment]
Hy everyone, are there any news here? :) Sounds really great

**Comment by israelmuca** [comment]
Hey guys! Anybody got it working with woocommerce?

**Comment by pkarw** [comment]
We will be publishing some limited integration in January

**Comment by israelmuca** [comment]
Awesome, I'm currently checking the project out with a possible customer, but their store is in woocommerce and they're not willing to switch.

Do you happen to have any more information regarding the limitations this integration will have?
So I can know if it will be possible to do so.

**Comment by pkarw** [comment]
Surely there will be lacking endpoints for customer account - addresbook, order history etc well point out what’s missed to make it easy to add it

**Comment by israelmuca** [comment]
Thank you so much, looking forward to try and help out with the rest of what's missing.

**Comment by pkarw** [comment]
Hi there! We’ve just published PoC of WooCommerce integration: https://github.com/DivanteLtd/woocommerce2vuestorefront; there are still tasks to be completed - listed in the: https://github.com/DivanteLtd/woocommerce2vuestorefront/blob/master/TODO.md. Please feel free to contribute (MIT license)

**Comment by lsimone** [comment]
Thanks for your effort @pkarw 
I read the README and the TODO of your project and I am wondering how mature your connector is, since I am evaluating to move from woocommerce frontend to vue-storefront one, but I have to be reasonably sure I will not have critical/blocking problems or limits in my future production platform, when I will finish it.

Could you please tell me if you think it could be production-ready and, if not, which effort is needed to complete your work?

**Comment by pkarw** [comment]
I @Isimone, I wouldn't say it's production grade. It's not and still lacking some important features - like order synchro. It's a good base for starting the development + then extending the connector, but probably not ready to be used out of the box as it just synchronizes the products.

**Comment by PierreVanvolsem** [comment]
Hi,
I appreciate your work. Are there still people supporting/working on it?
I have a lack of experience with all this new technologie. Any advice ?
Thank you !
