### ISSUE TITLE
Incorrect validation of the available qty (when changing the qty of the product in the cart)

### ISSUE THREAD

**Issue by GabiDivante** [DivanteLtd/vue-storefront#3083]
## Current behavior

There is incorrect behavior when I'm changing product qty typing unavailable qty and then trying to type again available qty. There is always a qty validation message visible. 
The example below for WS09-L-Blue - available qty in Magento = 83:
![Peek 2019-06-18 13-50](https://user-images.githubusercontent.com/49188852/59753749-14df6080-9285-11e9-840e-ed1cfa7641e1.gif)

## Expected behavior
The qty validation message is visible only when I type unavailable product qty. When I type/ choose available product qty - it is updated accordingly. 

## Steps to reproduce the issue

1. Go to WS09-L-Blue product page
2. Change Qty to 83
3. Click 'Add to cart'
4. Open cart
5. Try to change Qty to 84
6. Try to change Qty to 82 or any lower value 

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome 73
- OS: Ubuntu 18.04 LTS

**Comment by pkarw** [comment]
Plus: Adding to cart stopped working in the offline mode - needs to be checked

**Comment by GabiDivante** [comment]
@pkarw I checked on next and it works fine, where this issue appeared?

**Comment by pkarw** [comment]
@GabiDivante nevermind ;) I figured it out - it was not the offline issue but problem with my vs-api instance :)

**Comment by pkarw** [comment]
Hi @GabiDivante I've rechecked this one and here are my findings:

1. The validation is made on Magento2 side - we're sending a request to `cart/update` endpoint and Magento is responding with an error.

2. If You add the WS09-L-Blue with qty = 60; then modify to 20 - > it's fine, but when you add with qty = 60 and then modify to 30 - you got this error

3. It seems like Magento is validating the qty like existing item qty + ... the item you like to change to. Which makes no sense but this is the reason why 60+20 (80<83) works fine and 60+30 (90>83) is not.


This seems to be fixed with Magento 2.3 (and demo-magento2.vuestorefront.io is on 2.2); here's the original issue: https://github.com/magento/magento2/issues/12846
