### ISSUE TITLE
Agnostic CMS Content module

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#3112]
- Figure out proper data format (should it be cms-specific?)
- Implement component
- Repalce all the occurences of other CMS content usage with new component
- Make it compatible with all 3rd partys
- Figure out how CMS connector should work (agnostic regarding ES so common query format)

```html
<cms-content query="query">
// access to data, loading, error like gql components
</cms-content>
```

Routing for CMS pages can be done by having one route that takes the URL params and adds it as a query to the `cms-content` element

**Comment by benoitemile** [comment]
Hi, do you think we need to have content data in ES ?

**Comment by Zyles** [comment]
Here are my thoughts.

Content is more than text. It is:

1. Structure
1. Design
1. Text
1. Images

This includes CSS, HTML, images and links.

A visual builder is great for content managers, saving workload on developers.

Storing a text document is not enough, such as Markdown or otherwise.

Now I know this should be an agnostic module, but I am leaning very strongly towards Wordpress myself. And I will explain why so you can get some use cases.

My plan is to use Wordpress Gutenberg visual editor as the CMS backend.

The WP rest API would output rendered HTML which is then injected into a Vue component.

The component is called either by permalink URL in Wordpress or by ID. Or maybe it could sit in graphql and be fetched using an ID matching the Wordpress ID.

The important part is using some kind of widget system, so you can choose what content goes into what position on the frontend.

A rule engine like in Magento would be very nice. Because if you go and put Vue components all over the place manually. What happens when that content is obsolete and a content manager needs to delete it? A developer would have to edit the Vue template.

If you instead registered widget positions like "content.top". Then the content manager could say in the CMS "position: content.top; priority: 10" using priority to sort the content.

This approach gives us some very good bonuses:

1. Structure design of premade blocks is provided and managed by developers in Wordpress
1. A content manager can design content blocks without programming using the visual builder
1. The CMS is not tied to any ecommerce platform
1. The rendered HTML looks the same on the CMS and can be previewed, and be the same as the live store (if CSS styles are included)
1. The Wordpress ecosystem can provide custom blocks
1. Wordpress has support for custom taxonomies which are strong custom content types
1. The content manager decides where content goes, not the Vue developer (after initial widget placement)

I strongly believe in the output of rendered HTML from the CMS instead of building the visual design using Vue. Because if you do that, you will not have the same visual experience for the content managers as the CSS and HTML can differ making previews hard inside your CMS solution.

Now the hard problems:

1. Solving linking issues

Research needs to be done how the CMS links to things. Hopefully it uses relative links, but not all CMS do that.

When a user creates a link in the editor it may inject the full domain of the Wordpress installation in the rendered HTML, which requires rewrites of all URLs in the content.

2. Solving image issues

Where are images stored? When building content you would probably use the CMS media manager to insert image and align them where you want. When you import the rendered HTML you would need to download the images from the CMS into Vue Storefront and rewrite the URLs.

3. Caching

You should not call the CMS on every single page load. But if content changes it must somehow update the cache. Using a push technique from the CMS to update content is probably a good idea.

**Comment by pkarw** [comment]
@Zyles nice research is that a feature you're working on?

**Comment by Zyles** [comment]
@pkarw No not yet, we are still battling with Magento 2.3.3 frontend ... hopefully 2020 will be the year of headless.
