### ISSUE TITLE
Error on VPS / production setup -  DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.

### ISSUE THREAD

**Issue by protob** [DivanteLtd/vue-storefront#3190]
## Current behavior

I wanted to test Vue Storefront production setup on VPS.  
Site url: https://vue.emerg.pl
It uses default, demo products data.
The browser console shows an error and few service-worker.js warnings. 
The internal pages are not loading asynchronously. The urls are pushed to address bar, but only manual refresh can navigate to another page.
`"DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method."`

## Expected behavior

Internal pages should be loaded the "Vue way", asynchronously.  DOMException shouldn't show in the console.

## Steps to reproduce the issue

Please visit https://vue.emerg.pl and click any internal link.

## Can you handle fixing this bug by yourself?

- [ X] YES
- [ ] NO

## Environment details

VPS
Ubuntu Server 18.04.2. LTS
nginx v1.14.0
Node v8.16.0
yarn v1.16.0

Local Machine
Windows 10 PRO
Chrome 75.0.3770.100

**Comment by pkarw** [comment]
Please do check if you’re using the SSR cache if so then it may need to be cleared after the build (if this issue has been caused by he wrongly cached scripts references (as they’re hashed with the current build)). I can’t check it right now but, please do let us know if this issue is occurring only on your production setup or also on demo/next instances(?)

@alinadivante we need to verify this issue please

**Comment by protob** [comment]
Thanks for the fast reply. I modified only the config: local.json according to the official guide.
I solved the issue by fresh installation on another subdomain: https://vuesf.emerg.pl
Please close the issue or let me know if there is something i could check to provide valuable feedback from the buggy instance.

**Comment by pkarw** [comment]
Thanks for letting us know. Any feedback on what could caused this issue?
