### ISSUE TITLE
Product attribute not always showing up on category page

### ISSUE THREAD

**Issue by juho-jaakkola** [DivanteLtd/vue-storefront#3199]
I have a custom dropdown product attribute called `delivery_time`.

I am using this helper method: https://github.com/DivanteLtd/vue-storefront/blob/master/core/modules/catalog/helpers/optionLabel.ts to display the selected attribute option within each product tile on the category page.

However, something strange happens on the page. On the first page load I do not see the attribute value at all:
 
![Screenshot 2019-07-09 at 10 34 14 AM](https://user-images.githubusercontent.com/883920/60874190-ec210a00-a237-11e9-8b8d-3055a0c9590b.png)

After I click the filters a couple of times, the attribute appears, but only the ID of the value is displayed:

![Screenshot 2019-07-09 at 10 35 13 AM](https://user-images.githubusercontent.com/883920/60874516-74071400-a238-11e9-9069-3d7c0eecb224.png)

When I visit the product detail page, and come back to the category page, the value label is finally displayed as expected:

![Screenshot 2019-07-09 at 10 39 53 AM](https://user-images.githubusercontent.com/883920/60874603-9305a600-a238-11e9-9909-b8eda221d49f.png)

I have tried adding the `delivery_time` attribute in `config/local.json` to these sections:
 - `entities.productList.includeFields`
 - `entities.productListWithChildren.includeFields`

I have also tried whether the frontend visibility settings of the attribute within Magento 2 admin panel could affect this.

But none of these have any effect on the visibility of the attribute id nor its label.

Am I missing something, or what could explain this weird behavior?

**Comment by juho-jaakkola** [comment]
In my example I am using a custom theme, but I tested the same attribute also with the `theme-default` to make sure nothing has accidentally been broken within the theme.

**Comment by juho-jaakkola** [comment]
The "takes some effort" label was added? What exactly is causing the described problem?

**Comment by pkarw** [comment]
@juho-jaakkola i've just added a label to set the weight of this task in Github Issues, haven't had a chance to take a deeper tech look

**Comment by juho-jaakkola** [comment]
I added another attribute that has a simple integer value. That one appears on the category page as expected as long as I have added in into the `entities.productList.includeFields` array in `config/local.json`.

So could there be some problem specifically with attributes having multiple options?

**Comment by pkarw** [comment]
Hi there, for sure the attribute needs to be on the `entities.productList` and `entities.productListWithChildren` included. If it's not the `int` or `text` attribute (say: multivalue) it won't be automatically labeled across the `attribute` entities meta data. If it's simple attribute and it's integer and you're using `optionLabel` it should be displayed properly as long as you've got the attribute data loaded for this attribute.

category pages loads the attribute metadata for the attributes that are listed in the `config.products.defaultFilters` - so you can put this attribute in there in order to have it metadata listed properly or call the `attribute/list` manually

**Comment by juho-jaakkola** [comment]
The problem about the attribute labels should indeed get fixed once the issue #3220 gets fixed.
