### ISSUE TITLE
Pass `RouteManager` additionally to router to modules

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#3479]
## What is the motivation for adding / enhancing this feature?

@filrak currently, because of Multistore and optimizations made in #3443 we don't want users to call `router.addRoutes` directly; we should then pass `RouteManager` instead of plain `vue-router` into module constructors - especially that we have more/less the same interface so it's not a breaking change even

related to #3443 
related to #3454

**Comment by filrak** [comment]
@pkarw then we will loose a lot fo basic APIs from router. We can do this but I think we should make RouterManager a js proxy for router object and just proxy the addRoutes method. Then we can just export this proxy instead of a router everywhere. By doing this we are hiding unnecessary complexity and not confusing ppl that there is a router and RouterManager, wdyt?

**Comment by pkarw** [comment]
I like the idea with proxy; can you mock it up please?
