### ISSUE TITLE
@vue-storefront/cli init:module

### ISSUE THREAD

**Issue by undefinederror** [DivanteLtd/vue-storefront#3567]
I am following the VueStoreFront Cookbook, and at [Ch5 1 2-2. Recipe B (CLI bootstrapping) 2](https://docs.vuestorefront.io/guide/cookbook/module.html#_2-1-recipe-a-manual-bootstrapping) it reads:

> Run the vsf CLI command as follows :
`vsf init:module example-folder`

## Current behavior
```
$ vsf init:module example-folder
Unknown command. try one of those:

Usage: vsf [command] [options]

Options:
 --help         available commands
 --version      CLI version

Commands:
 init [dir]     setup new VS project
```
## Expected behavior
`vsf init:module <folder>`  should be a known command

## Version
@vue-storefront/cli@0.0.15

**Comment by pkarw** [comment]
@kkdg Degi can you take care of this one?

**Comment by kkdg** [comment]
@pkarw sure thing. stacked. thanks

**Comment by kkdg** [comment]
@undefinederror @filrak I found this happened because your version is too low to execute that command. It's not your fault, and of none either. I found even the latest npm package doesn't contain the script it needs to run `vsf init:module example`. However, if you checkout _Vue Storefront_ to `develop` branch, there you can find `./packages/cli/index.js` which contains the script to run the command. 

So you can do either of two options : 
1 of which is wait until the new version comes out (I am not in charge of the feature release schedule, but I am sure this will be out very soon). or,
2 of which is run the command at `./packages/cli/index.js` on `develop` branch.

**Comment by undefinederror** [comment]
Thank you @kkdg, 

I didn't understand the `cookbook` section is meant to apply to a future release, my bad.
I think I am going to be patient and just wait for the module to be published on npm.

Thank you
