### ISSUE TITLE
[docs] 2-1. Recipe A (Manual bootstrapping) outdated

### ISSUE THREAD

**Issue by undefinederror** [DivanteLtd/vue-storefront#3570]
[2-1. Recipe A (Manual bootstrapping)](https://docs.vuestorefront.io/guide/cookbook/module.html#_2-1-recipe-a-manual-bootstrapping) seems to be outdated.
## Current behavior
> 3.1 Open that file and write down the minimum signature of a module
>
> ```javascript
> import { StorefrontModule } from '@vue-storefront/core/lib/modules';
> export const ExampleModule: StorefrontModule = function (app, store, router, 
>      moduleConfig, appConfig) {
> }
> ```
## Problems
- '@vue-storefront/core/lib/modules' doesn't exist, I can find 'module'
- `StorefrontModule` isn't there, I can find `VueStorefrontModule`
- The implementation in docs is generally very different to what I can see in the repo, where it uses sometimes `createModule()` (like in /src/modules/claims), sometimes `new VueStorefrontModule()` (like in /src/modules/google-tag-manager)

I have literally just started out with VSF and find this a bit confusing

## Expected behavior
Docs should reflect the current codebase

## Environment details
Version: 1.10.2

**Comment by kkdg** [comment]
@undefinederror Thank you for the issue, btw, can you clarify which branch are you on?

**Comment by kkdg** [comment]
To be clear, `cookbook` is based on the massive change VSF is going to take soon, (maybe it was planned for earlier, but you know "development") which means, it's based on `develop` branch. I am afraid you are on `master` branch, that's why you see such mismatches in code base so I think your title should be better written from _outdated_ to _predated_ 
You are ahead of other people and preparing for the future. ;) Thanks.

**Comment by undefinederror** [comment]
Hi @kkdg,

Thank you for clarifying this. Yes I am indeed on the `master` branch. Seeing discrepancies in the `cookbook` docs, not knowing any better, I assumed it was old information.

All clear now, I have amended the issue title :)

Thank you
