### ISSUE TITLE
Browser History partially broken, back working but forward not

### ISSUE THREAD

**Issue by nhp** [DivanteLtd/vue-storefront#3642]
## Current behavior
If going from some dynamic link to another, like click through categories, or going from category to a product and using the browser:back functionality everything is fine. But after using browser.back there is just a short "flicker" of the browser:forward button and afterwards it is not usable. Browser:back keeps working.
Originating from static links, like homepage, going to a product > browser:back results in a working browser:forward mechanic.

## Expected behavior
After using browser:back every page should be able to have a sane browser history and be able to use browser:forward.

## Steps to reproduce the issue
From home, use a category from the menu, click on a product, use browser:back and browser:forward is not working.
Coming from home, going directly to a product > browser:back then browser:forward is working.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
- Browser: chrome
- OS: linux

**Comment by pkarw** [comment]
@nhp this is something you observerd only on develop or also on master branches? @andrzejewsky it's maybe related to the issue your're working on

**Comment by ResuBaka** [comment]
@pkarw I have just tested it on demo as we could not test it when the issue was written (demo page had errors). On there I can see the same issue.

**Comment by andrzejewsky** [comment]
yeahh I had something similar either, seems like there is seriously something wrong, I'll try to figure out where is the problem

**Comment by andrzejewsky** [comment]
@nhp I've came across why `browser:forward` doesn't work. Basically this line: https://github.com/DivanteLtd/vue-storefront/blob/develop/core/modules/url/router/beforeEach.ts#L35 is responsible for it. We calling `next` when some route was changed which means that we always put this route on the top of the history stack.

So when you trigger `browser:back`, the route which you are going to is added to the top while it supposed to just rewind in the history. As a result, the first route in the history is that one you just entered (by `history:back`). That's why `forward` button in the browser is inactive (there is no forward route).

Of course I'll try to find some solution / workaround, but if it demands some significant changes in the routing, we probably won't solve this now.
