### ISSUE TITLE
Create an `default-optimized` theme based on `default`

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#3963]
## What is the motivation for adding / enhancing this feature?

We can use theme inheritance (https://www.yireo.com/blog/2019-11-19-vue-storefront-theme-inheritance) to create a second theme `default-optimized` which could limit some non-frequently used features in order to limit the bundle size.

Some ideas for the optimizations:
- override the `Product.vue` (or some part of it) and disable the `wishlist` and `compare` modules
- remove Product Reviews,
- remove Newsletter integration,
- ...

**Comment by pkarw** [comment]
... it should be a second theme, because in the standard `default` all the features should be still available to use

**Comment by pkarw** [comment]
Other ideas for optimizations:
- remove offline orders feature,
- optimize bundle size and remove localStorage (keeping just the localStorage support directly in the storage.ts)

**Comment by andrzejewsky** [comment]
Actually makes sense for me, but maybe it's high time to introduce theme-related config file, and we can on/off some features there instead of writing a new theme? What do you think @pkarw?

**Comment by pkarw** [comment]
@andrzejewsky that's surely good idea - another one: have `src/modules/index` file per theme - to disable the modules not necessarily needed for a particular theme

BUT - there is a lot of things you can't disable via config or it would be too complex; say: removing product reviews - it's far easier to just remove the `<product-reviews` within the `Product.vue` which is separated to this dedcated theme; isn't it?

**Comment by gibkigonzo** [comment]
Would be super cool if we could generate theme by cli (and also a theme config). For example:
1. `vsf init:theme` - always generate base theme with Product, Category, Cart, Checkout
2.  additional options which would add code to template and import modules
```
// theme.config.js
modules: ['home', 'wish-list']
```
If someone would like to add in future more modules, then would need to add it in theme config (to import logic) and manually add proper component in template. It would make task much much (:smile:) more complex, but would not increase theme complexity.

**Comment by grimasod** [comment]
How about a `minimal` theme that `default` inherits from?

- A barebones theme (minimum necessary layout, highly optimized)
- Includes basic functionality (Vuex getters, data prefetching, etc)
- Separate  Component, JS, and CSS files

It's easier to explain by example. In situations where we just want to change the Product page layout a little, or tweak the CSS, or change one function...

Currently we have no choice - we have to copy the `pages/Product.Vue` component into our theme to make the changes. When the next version is released, we have to compare the entire file line-by-line, to see what has changed and decide what to merge into our custom version. It's very time consuming with are about 160 components. We saw a lot of this with the recent v1.11 release. And this will continue to be more complicated because a lot of functionality has moved from core mixins to theme components.

With separated files and inheritance, we would only need to add the files that we need to change, making it much easier to upgrade to later versions.

Here's a rough idea of how it might work (not tested at all)

- `src/themes/minimal/pages/Product.vue`
```
<template>
  <div>...</div>
</template>
<script>
import Product from 'theme/pages/product/product.js'
export default {
  mixins: [Product]
}
</script>
<style src="./product/product.css" lang="scss" scoped></style>
```
 
- to change or add functionality (JS only), just create a custom `Product.js` file in the theme (using inheritance). The default `Product.js` can optionally be used as a mixin in the custom `Product.js`.

- to change the HMTL output, create a custom `Product.vue` file in the theme (using inheritance). The default `Product.js` can be imported and, if required, can be overridden or extended too

 - to change the CSS, also create a custom `Product.vue` file in the theme (using inheritance). The default `product.css` can be imported and overridden, or completely custom CSS can be used.

At first, probably all themes would need to inherit from the `minimal` theme, but with some further work, it might be possible to have multiple level inheritance. So theme developers could choose to inherit from the `minimal` theme or from the `default` theme (which inherits from `minimal`).

**Comment by pkarw** [comment]
@grimasod that's actually a good idea but I'm afraid of the complexity of refactoring the `default` page and the backward compatibility problems this re-architecture migh case (?)

So, maybe we created a `minimal` theme - and have all the customization options you described - but without refactoring the current default (?)

So if someone will be creating a theme can use the `minimal`. I see it as taking the `deafult` ans stripping it down

**Comment by pkarw** [comment]
@gibkigonzo 
@andrzejewsky wdyt?

**Comment by grimasod** [comment]
@pkarw Thanks for the feedback

I think it should be possible to make it 100% backward compatible. Every component could still be in the `default` theme. The main difference is that it would inherit JS from the `minimal` theme. I haven't tested this idea though ;)

> I guess someone might want to inherit from `default` as well.
Yeah. Ideally they could choose either to inherit from.

> But refactoring `default` to this inheritance model is a lot of work
That's true! But might be worth it in long run 

> will make upgrades harder
The motivation for my suggestion was to make upgrades easier for custom themes. I understand that it might make it harder for the core upgrade, but maintaining 2 completely separate themes, `default` and `minimal` (or `default-optimized`) could be quite complicated too.

**Comment by grimasod** [comment]
Here's another idea...

How about a minimal theme module? In other words a module that contains mixins for every component (that has JS), including pages. The components in a minimal theme only contain HTML and CSS (plus one mixin import). All other themes could use the same mixins and extend / override as required.

**Comment by pkarw** [comment]
This idea is being partially implemented (just the optimization ideas) as part of new optional theme we are building at the moment: https://github.com/DivanteLtd/vsf-capybara

**Comment by lukeromanowicz** [comment]
If I may, I suggest naming `default-slim` or `default-light` instead of optimized.

**Comment by pkarw** [comment]
I'm closing this task as for now - the [Capybara theme](https://github.com/DivanteLtd/vsf-capybara/issues) is the theme were we put quite a lot of optimizations already. Of course separating the minimal/default theme still makes sense however as the core team we probably won't have the capacity to take care of it - being focused on the [optimization tasks](https://github.com/DivanteLtd/vue-storefront/issues/3949) for 1.12
