### ISSUE TITLE
Error: Cannot find module '/var/www/share/<SERVER>/vue-storefront/core/scripts/server.js'

### ISSUE THREAD

**Issue by upandfine** [DivanteLtd/vue-storefront#4190]
Context: https://docs.vuestorefront.io/guide/installation/production-setup.html#production-setup-bare-vps

(git master, fresh installation)
Steps to reproduce:
1. yarn install
2. yarn build 
3. yarn start

After a few seconds all nodes switch to "errored.

[log.txt](https://github.com/DivanteLtd/vue-storefront/files/4360931/log.txt)

**Comment by pkarw** [comment]
@kkdg can you please check it? @upandfine from quite some time the script was renamed to `server.ts` - maybe you updated your instance and need a `pm2 reload all` in order to get the right pm2 configuration in place? That's pretty strange

**Comment by kkdg** [comment]
Got it, looking over error logs

**Comment by upandfine** [comment]
> @kkdg can you please check it? @upandfine from quite some time the script was renamed to `server.ts` - maybe you updated your instance and need a `pm2 reload all` in order to get the right pm2 configuration in place? That's pretty strange

Already done. Also pm2 restart all.
My webhoster (managed server) has also looked at the situation and found no solution. Other customers run on the previous version.

**Comment by kkdg** [comment]
Hi, @upandfine I reinstalled this on a fresh linux instance without docker multiple times but it was working smoothly all the time. 
The only possibility for this error I could guess was `pm2` tracking cache instance so your older version of VSF affects your current run in case you ran it with an older version on the same instance. Or did you pump your data into ES correctly? You can try the sample data, but you should be careful since the ES version matters here, 
If your ES version is above 6, you should use `db7` command while lower than 6 should use `db`.

**Comment by upandfine** [comment]
I found the error.
The default configuration of pm2 in the home directory was broken/wrong. I renamed ~/.pm2 and it worked. Thanks for your great help and your effort - may it help the next one.
