### ISSUE TITLE
Microcart component styling

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#46]
We need to style Microcart component according to Figma. 
Thiis task includes creating all components required for microcart to look like in Figma

**Comment by pkarw** [comment]
Let me know if you need any summary / totals info here.

Another thing is that we need to show the prices incl tax. As there is general problem with tax regarding Magento2 API (https://github.com/magento/magento2/issues/7207) we'll need to extend an API for `priceInclTax` field 

**As for now let's not worry about it.** Instead please provide the Vuejs helper/filter for displaying prices, that get's the whole product object as an input; the second helper should be only for formatting the price itself

@bpicho Bartek would you, or anybody else be able to help us with this API extensions? Also regarding #51 - that would be great

@filrak @patrykpiston then we have to decide if we're going with some domain model objects regarding (for example) this pricing issue - #43; because as for me - moving every piece of logic to external helper rather than having model methods seems like not so OOPish approach to development

**Comment by filrak** [comment]
@pkarw totals() still doesn't work. Will you fix it?

**Comment by pkarw** [comment]
@filrak sure. As for now could you please just return some static JSON there to mark the format you require?

**Comment by filrak** [comment]
@pkarw sure, i'll do it today ;)

**Comment by pkarw** [comment]
@filrak and how are things here? :)

**Comment by patrykpiston** [comment]
I've stylized the microcart component with static data (besides of the products visible). Products display only the name, sku and quantity for now.

PR  #69

**Comment by patrykpiston** [comment]
Closed by #69
