### ISSUE TITLE
NVM + yarn global add @vue-storefront/cli@next doesn't expose "vsf" binary

### ISSUE THREAD

**Issue by sudo-at-night** [DivanteLtd/vue-storefront#4866]
## Current behavior
1. Install `yarn global add @vue-storefront/cli@next`
2. Run `vsf`
3. Results in `Command 'vsf' not found, did you mean: [...]`

## Expected behavior
1. Install `yarn global add @vue-storefront/cli@next`
2. Run `vsf`
3. Results in `ERROR  VSF Provide command`

## Steps to reproduce the issue
Steps described above in **Current behavior** and **Expected behavior** sections

## Version of Vue Storefront

- [ ] Vue Storefront
- [x] Vue Storefront Next

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Environment details
- OS: Ubuntu 18.04 
- Node: v14.5.0 and v14.10.1

## Additional information
Problem does not occur when using NPM to install the CLI package.

Even though Yarn informs that the binary was installed, it's unavailable. Example installation log:
```sh
success Installed "@vue-storefront/cli@2.0.3" with binaries:
      - vsf
```

**Comment by Fifciu** [comment]
Please open terminal and run:
```sh
yarn global bin
```
Then:
```sh
echo $PATH;
```

I bet you do not have yarn global binaries in your path - that's why you cannot run it from any place. More about this [here](https://github.com/yarnpkg/yarn/issues/648)

To solve this you should modify your `$PATH` variable. You could use (just tested it on Ubuntu 20.04):
```sh
export PATH="$(yarn global bin):$PATH"
```

Unfortunately, it will work only for the current terminal. If you want to have it permanently, you want to modify your `~/.bashrc`. More about this [here](https://stackoverflow.com/questions/14637979/how-to-permanently-set-path-on-linux-unix)

**Comment by sudo-at-night** [comment]
@Fifciu Yep, that was the issue, thanks :slightly_smiling_face:
