### ISSUE TITLE
Add one product box - like in the design

### ISSUE THREAD

**Issue by mercs600** [DivanteLtd/vue-storefront#587]
Improvement moved from #456

![zrzut ekranu 2018-01-24 o 22 12 52](https://user-images.githubusercontent.com/7935392/35357438-ce1d4f40-0153-11e8-98b9-1535e61e7819.png)

**Comment by filrak** [comment]
Isn't it just a product tile for 12 cols? We can add just one optional prop to the ProductTile.vue that makes image bigger and voila ;) (i amde something similar in vue-catalog theme - check [ProductTile.vue](https://github.com/DivanteLtd/vue-storefront/blob/master/src/themes/catalog/components/core/ProductTile.vue) and `mobileHorizontalMode`)

**Comment by Aekal** [comment]
It's not that simple, because col-xs is placed outside the component.
`ProductTile` is in `ProductListing` which is used in few places, so I think we shouldn't edit class there.
I can just make every 3rd product in `ProductListing` wider on mobile but is it expected behavior? Or only products with 'Sale' label should be wider?
