### ISSUE TITLE
Move css properties to atomic css classes in default theme

### ISSUE THREAD

**Issue by Aekal** [DivanteLtd/vue-storefront#634]
I think we should check existing vue components in default theme and move some css properties from `<style>` to classes in `<template>` as described in [docs](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/themes/default/Working%20with%20stylesheets.md).

**Comment by Aekal** [comment]
I'll take care of it

**Comment by filrak** [comment]
I was thinking about it since november but had no time, great to hear that you will take care of it. Can you also change classes connected to colors to more generic? (c-primary c-secondary etc). With classes like this the theme will be much more customizable. Taka a look at vue-catalog theme and try to do sth similar ok?

**Comment by Aekal** [comment]
We can work on it later, as we discussed it'll be better to create separate issue for this.

**Comment by filrak** [comment]
@Aekal can i close the issue?

**Comment by Aekal** [comment]
Yes, we can close it
