### ISSUE TITLE
[i18n] Create German translation

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#694]
Working with translations is pretty easy with Vue Storefront, take a look at: https://github.com/DivanteLtd/vue-storefront/blob/master/doc/i18n/Working%20with%20translations.md for reference

**Comment by EliasKotlyar** [comment]
Hello ,

I have started work on this Feature. Due to the fact that the translation files are provided in only one file and also only in JSON, i decided to refactor them to CSV. I have completed this task, but unfortunately, i struggled integrating a solution which will use all CSV-Files from a directory. It should be possible with this Plugin:
https://www.npmjs.com/package/babel-plugin-wildcard

I suppose that its a general issue, and therefore it needs to be done in another ticket...

**Comment by pkarw** [comment]
Ok I think that it’s good enough to just include the selected locale file as you already made it work within the latest PR. We just need to merge in the new translation strings

**Comment by EliasKotlyar** [comment]
Hello @pkarw ,

Thanks your for merging the CSV-Feature. Now i would love to provide the german-translations. I would use the following Saas:
https://crowdin.com

Magento is using it(https://crowdin.com/project/magento-2), and i suppose its a good way to create localisation.

What do you think about it? Its completely free for open source projects.

Greatings
Elias

**Comment by pkarw** [comment]
Thanks for your effort! I think it's good move with standardized CSV format.

Please go ahead with crowdin

**Comment by EliasKotlyar** [comment]
Okey, i have linked my repository to the crowdin. Now everyone can contribute to the translation process:
https://crowdin.com/translate/vue-storefront/5/en-de

**Comment by pkarw** [comment]
Great job @EliasKotlyar thanks!

**Comment by pkarw** [comment]
@EliasKotlyar could you please add other languages to the project (Spanish, French, Polish)?

**Comment by EliasKotlyar** [comment]
Hello @pkarw ,

I have requested Access trough the Crowdin Github Integration to link it directly to this repository. Afterwards it would be easy to provide Translations. Feel free to contact me in Slack if there are any issues.

Greatings
Elias
