### ISSUE TITLE
Make extensions a separate npm packages

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#720]
Requires https://github.com/DivanteLtd/vue-storefront/issues/705

**Comment by MikeSheward** [comment]
We will be creating the Stripe Extension as a seperate NPM package to kickoff this. 👍

**Comment by pkarw** [comment]
@MikeSheward it's cool; so I've assigned this one to You

**Comment by Igloczek** [comment]
It's related to #729 so I'll take it over

**Comment by pkarw** [comment]
@Igloczek @filrak @MikeSheward  I've done this with #878

Because of the web pack nature (doesn't support dynamic import / require) I had to modify the extension loader - moving enabled extensions from config/local.json to /extensions/index.js 

Otherwise, it wouldn't have been possible to load extensions installed via npm like - https://github.com/develodesign/vue-storefront-stripe

By the way - I've added dependency to vue-storefront-stripe by default @MikeSheward - good job :)
