### ISSUE TITLE
Publish the npm package

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#753]
As the core is now separated we just need to:
- [ ] create a build / boilerplate copy script
- [ ] run npm installer script in post install step
- [x] create npm account and publish the package

Then to consider if we need to:
- add interactive setup to check if user need to create boilerplate (99% cases) and if to run the installer
- add theme selector to the installer script

**Comment by Igloczek** [comment]
How we would like people to set up this project in the future?
1. Run `npm install vue-storefront` on a clean project, then the same way add themes and extensions. It will require some, probably serious, changes, but will keep the core safe from unwanted modifications and make shipping updates easier.
2. Create a Vue CLI template `vue init vue-storefront` form the current state, the extensions and themes will be config options, but... it doesn't change much, because we still will not be able to easily ship updates to the existing installations.

Also, the question is how the plan of publishing packages looks like?
I'd opt to keep this stuff as separate repos, rather than using stuff like [lerna](https://github.com/lerna/lerna) and keep everything here.

PS. IMO that's the crucial stuff that needs to be done before releasing 1.0.

**Comment by pkarw** [comment]
@filrak has a plan for it (more like opt. 1 - "npm install vue-storefront" and if you didn't have it before it will create the boilerplate by creating the folders /src, /extensions, /core ... the core folder will be overridden after each npm update / npm install if we publish new version of the core). Is a solution that needs to be polished  - for example we need to have each theme as separate npm , the same with extensions. We won't be able to do all these refactors before 1.0 so we decided that's better to have a NPM distribution with sthh. that can be easily updated by npm rather than to have an ideal solution  :)

**Comment by Igloczek** [comment]
Something that for sure is worth to investigate in future is the `vue-cli@3.0.0`.
It's currently in beta, but seems to have all features necessary to abstract configuration, setup project and make updates possible.

**Comment by pkarw** [comment]
Blocker: #918 

@Igloczek are you on this maybe?

**Comment by filrak** [comment]
@Igloczek it's rather easy to migrate to vue-cli 3.0 if we will have some webpack magicians.

For now I think we should just create npm package with core folder (npm ignore for everything else - it will remain just for development purposes) and prepare some boilerplate template on other repo with structure similar to current `src` folder). WDYT?

**Comment by Igloczek** [comment]
After some research, I think that releasing the current version of the core as npm package make no sense at all.

- all dependencies are added in the root, so core itself is useless
- webpack works as a standalone tool, it's hard to use it from outside or customize - we will need to build something like Nuxt, which at least for me, is too complicated - https://github.com/nuxt/nuxt.js/tree/dev/lib/builder
- copying or symlinking everything from `node_modules` to users project is, for me, too hacky, error prone and agains the idea leting the npm to magane packages

So looking at all those problem, I'll try to investigate possibilietes of creating template using vue-cli.

BTW. I created `vue-storefront` organization on npmjs.com, so lets send me your emails I'll add you as admins/owners. Also the previously published https://www.npmjs.com/package/vue-storefront package should be removed, b/c it's not ready to use in this form.

**Comment by pkarw** [comment]
I'm closing this it makes no sense for now to invest more time int oseparating core as npm just for the sake of separate core module :)
